export interface Attendee {
  id: string;
  firstName: string;
  lastName: string;
  jobTitle: string;
  company: string;
  companySize: string;
  industry: string;
  hiresPerYear: string;
  regionalRemit: string;
  decisionLevel: string;
  activeProjects: string;
  activeProjectBudget: string;
  meetingObjective: string;
  budgetAuthority: string;
  assessmentTools: string;
  ats: string;
  crm: string;
  marketIntelligence: string;
  otherTools: string;
  solutionAreas: string;
  painPoints: string;
  projectStage: string;
}

export const attendees: Attendee[] = [
  {
    "id": "201697440144",
    "firstName": "Ciaran",
    "lastName": "O'Regan",
    "jobTitle": "Director, Talent Acquisition",
    "company": "the LEGO Group",
    "companySize": "20,001-50,000",
    "industry": "Retail",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA,UK,LATAM,North America,UK&I,APAC,MENA",
    "decisionLevel": "Key Influencer",
    "activeProjects": "Assessments, Structured Interviews, Candidate Experience Tools",
    "activeProjectBudget": "£50-100k",
    "meetingObjective": "Understand new tech and how these can solve future problems given advances in AI",
    "budgetAuthority": "< £50k",
    "assessmentTools": "HireVue, Internal Interview Toolkit",
    "ats": "Workday",
    "crm": "N/A",
    "marketIntelligence": "LinkedIn Talent Insights, internal analytics and insights team using PowerBI",
    "otherTools": "",
    "solutionAreas": "Assessments",
    "painPoints": "Detecting signal from high volume of applicants.  Looking at assessment technology that enables us to select the right candidates without effecting candidates experience negatively. \n\nTools to help with scaling structured interviews. ",
    "projectStage": "Planning & Budgeting (3-6 Months)"
  },
  {
    "id": "200923910443",
    "firstName": "Nuria",
    "lastName": "Munoz",
    "jobTitle": "Head of Talent Acquisition Europe and Latin America",
    "company": "Munich Re",
    "companySize": "50,001-100,000",
    "industry": "Insurance",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA,UK,LATAM,UK&I",
    "decisionLevel": "Direct Approver",
    "activeProjects": "SF migration to Smart Recruiters , Referral Platforms, GenAI for Recruitment , TA TOM, Early Careers , candidate assessment tools ",
    "activeProjectBudget": "£500k-£1m",
    "meetingObjective": "to secure a clear understanding of technology changes, success business cases and processes across the function ",
    "budgetAuthority": "£500K-£1m",
    "assessmentTools": "Various vendors across the world, non consistent ",
    "ats": "Success Factors ",
    "crm": "None",
    "marketIntelligence": "Cobrainer",
    "otherTools": "",
    "solutionAreas": "AI, Early Careers , Data Analytics for TA",
    "painPoints": "The entire organisation is going under HR Transformation, there are multiple needs , from systems that do not speak to each other, to lack of data and processes in place. From a TA perspective Early Careers is an area of investment and potential AI near future to support recruitment ",
    "projectStage": "Planning & Budgeting (3-6 Months)"
  },
  {
    "id": "200101377371",
    "firstName": "Jessica Shaunie ",
    "lastName": "Green",
    "jobTitle": "Head of talent acquisition",
    "company": "Calor gas ",
    "companySize": "5001-10,000",
    "industry": "Oil & Energy",
    "hiresPerYear": "1001-2000",
    "regionalRemit": "EMEA,UK,UK&I",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "EVP, AI integration, process streamlining without compromising experience of the candidate, ",
    "activeProjectBudget": "> £1m",
    "meetingObjective": "Automisation and technology is a huge focus this year to incorporate. EVP too and our market brand, our CEO has put this into all leaders across the business KPI’s for this financial year ",
    "budgetAuthority": "> £1m",
    "assessmentTools": "Korn ferry ",
    "ats": "Workday ",
    "crm": "Pageup ",
    "marketIntelligence": "N/a",
    "otherTools": "",
    "solutionAreas": "ATS system, AI automisation, EVP, candidate experience",
    "painPoints": "Brand awareness and marketing of our great culture. Technology to help the recruiters becoming business partners ",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "195183358360",
    "firstName": "Anna",
    "lastName": "Katyal",
    "jobTitle": "Head of Talent Acquisition",
    "company": "BMS Group",
    "companySize": "1001-2500",
    "industry": "Insurance",
    "hiresPerYear": "251-500",
    "regionalRemit": "UK,North America,APAC",
    "decisionLevel": "Key Influencer",
    "activeProjects": "Applicant Tracking System selection, Strategic hiring projects for growth",
    "activeProjectBudget": "£50-100k",
    "meetingObjective": "I want to understand how to become more efficient with the TA team, to increase quality of data in reporting and systems use, how to provide a consistent recruitment process globally no matter the location, how to increase ROI, dashboard value and reduce recruiter admin",
    "budgetAuthority": "< £50k",
    "assessmentTools": "N/A",
    "ats": "N/A",
    "crm": "N/A",
    "marketIntelligence": "N/A",
    "otherTools": "",
    "solutionAreas": "Recruitment system and database, process for maximum efficiency",
    "painPoints": "Talent Acquisition in BMS Group is still quite new, and our processes are manual without an ATS. Reporting is difficult, reliance on agencies is still there, and a lack of understanding of broader Talent Acquisition strategies and solutions in insurance and other industries proves to be difficult to inspire solutions for our own team. Quality of candidates in certain areas is decreasing, yet applications are on the rise which proves to be a distraction from hiring the top talent and key strategies of doing this, keeping key talent warm for when it may be the right time and what systems TA have in place to maximise efficiency. Investors are requesting better data, improved reporting, a shorter time to hire to remain competitive.",
    "projectStage": "Planning & Budgeting (3-6 Months)"
  },
  {
    "id": "194698768792",
    "firstName": "Nainik",
    "lastName": "Patel",
    "jobTitle": "Delivery Lead, Head of Global Talent Acquisition ",
    "company": "Hitachi ",
    "companySize": "100,000+",
    "industry": "Information Technology and Services",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA,UK,North America,UK&I,APAC,MENA",
    "decisionLevel": "Direct Approver",
    "activeProjects": "…",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "Building value case to introduce Ai/Technology to attract and retain talent  ",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "…",
    "ats": "Workday ",
    "crm": "…",
    "marketIntelligence": "…",
    "otherTools": "",
    "solutionAreas": "…",
    "painPoints": "Candidate/new joiner and hiring manager experience ",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "194295425320",
    "firstName": "robyn",
    "lastName": "collins",
    "jobTitle": "VP TA",
    "company": "M42",
    "companySize": "20,001-50,000",
    "industry": "Hospital & Health Care",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA,UK,LATAM,North America,UK&I,APAC,MENA",
    "decisionLevel": "Direct Approver",
    "activeProjects": "Review of iCIMS with a view to replace, deploy Findem for sourcing tech.",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "To meet liked minded global TA to network and learn, solve real tangible issues.",
    "budgetAuthority": "> £1m",
    "assessmentTools": "Building a global bank of assessments by function and level",
    "ats": "iCIMS and Success Factors",
    "crm": "iCIMS Jibe",
    "marketIntelligence": "NIL",
    "otherTools": "",
    "solutionAreas": "I am currently focused on building stronger recruiter and manager capability (building a \"licence to hire\" series) while redesigning the recruitment process namely for volume hiring, moving away from CV driven, application heavy processes using SJT and conversational AI and automated interview scheduling to replace resume applications with faster, more human decision making. ",
    "painPoints": "Talent Acquisition operates at significant scale across trad healthcare, technology, and science/research, creating a set of interconnected challenges. Hiring demand is high, urgent, and specialised, while traditional recruitment models remain too resume driven, reactive, and process heavy to keep pace. Manager capability in hiring is inconsistent, leading to variable assessment quality, cost driven, and poor decision making.\nCandidate experience is fragmented due to legacy application flows and manual touchpoints.\nFinally, data and technology are under utilised, limiting visibility on impactful data making it harder to shift from transactional recruitment to a scalable, intelligence led talent engine.",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "192303904943",
    "firstName": "joanna",
    "lastName": "saunders-hare",
    "jobTitle": "Executive Director, Talent Acquisition",
    "company": "MUFG, Mitsubishi UFJ Financial Group.",
    "companySize": "1001-2500",
    "industry": "Financial Services",
    "hiresPerYear": "1001-2000",
    "regionalRemit": "Other",
    "decisionLevel": "Direct Approver",
    "activeProjects": "5",
    "activeProjectBudget": "> £1m",
    "meetingObjective": "Defining the next 3-5 transformation plan for Talent Management (Acquisition & Development) ",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "Assess Candidates ",
    "ats": "Smart Recruiters",
    "crm": "Smart Recruiters",
    "marketIntelligence": "LinkedIn Insights ",
    "otherTools": "",
    "solutionAreas": "AI, skills gaps & new market insights, end2end Talent Management, ROI on hire ",
    "painPoints": "Identifying creative scalable tech to make hiring decisions. Upskilling TA teams to be consultative, using predictive analytics to build hiring strategies,  Quantifying skills gaps in talent pools, and plugging skills gaps. Identifying  new markets for growth with robust data,",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "190898269597",
    "firstName": "Jonathan",
    "lastName": "Kitterhing best",
    "jobTitle": "Global head of Talent Acquisition",
    "company": "Swiss Re Management Ltd",
    "companySize": "10,001-20,000",
    "industry": "Insurance",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA, LATAM, North America, UK&I, APAC, MENA, Other",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "TBC",
    "activeProjectBudget": "< £50k",
    "meetingObjective": "Undertsand others approach to TA Skill based hiring, EU Pay Directive and AI in TA",
    "budgetAuthority": "£50-100k",
    "assessmentTools": "RR bespoke, Hogan, SHL",
    "ats": "SAP SSF",
    "crm": "Phenom",
    "marketIntelligence": "SSF module",
    "otherTools": "IN house built Textio type tool, Talent Neuron, LI Insights, Social Talent",
    "solutionAreas": "Ai, Automation, org redesign to reduce HC",
    "painPoints": "Ai, Simplification of tech stack to reduce HC. implementing Phenom with SAP SSF in place",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "185464523694",
    "firstName": "David",
    "lastName": "Nottage",
    "jobTitle": "Head of TA",
    "company": "Screwfix",
    "companySize": "10,001-20,000",
    "industry": "Retail",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Automation\nATS config and optimisation\nEmployer branding strategy\nTalent mapping and workforce planning \nSkills gap analysis and assessments",
    "activeProjectBudget": "> £1m",
    "meetingObjective": "I would like to have some conversations about not only solutions to issues we have now, but where are we going and how do I future proof the TA function for not only Screwfix, but also the wider Kingfisher Group including B&Q, Screwfix, Brico and more.",
    "budgetAuthority": "£500K-£1m",
    "assessmentTools": "Multiple",
    "ats": "iCIMS",
    "crm": "SAP",
    "marketIntelligence": "N/A",
    "otherTools": "Various, but nothing outstanding",
    "solutionAreas": "all of the obove",
    "painPoints": "I currently have a group wide ATS system, that si clunky so am working with them to maximise the potential of the system. In terms of the team,  they are very immature in terms of TA and have been doing a lot of manual processes. I am really interested in AI, releasing the teams to do more work that matters and thinking about the role we have to play both in talent acquisition and talent rejection.",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "183232510638",
    "firstName": "James",
    "lastName": "Kennedy",
    "jobTitle": "Talent Acquisition Director, EMEA",
    "company": "Palo Alto Networks",
    "companySize": "10,001-20,000",
    "industry": "Information Technology and Services",
    "hiresPerYear": "501-1000",
    "regionalRemit": "EMEA, UK, UK&I",
    "decisionLevel": "Direct Approver",
    "activeProjects": "Data Governance, AI, EUPT",
    "activeProjectBudget": "< £50k",
    "meetingObjective": "I want to ideally learn from others who have implemented Workday Recruiting, alongside Paradox and HiredScored, their lessons learned and watch outs. Keen to learn also about how folks in enterprise size businesses have embedded AI into the hiring process in meaningful way that has driven ROI for TA and the business.",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "HiredScore",
    "ats": "Workday",
    "crm": "Workday",
    "marketIntelligence": "None",
    "otherTools": "Paradox",
    "solutionAreas": "Top of funnel AI-enabled screening is of interest.",
    "painPoints": "About to implement WorkdayRecruiting, Paradox and HiredScore which in itself is a challenge. Leading a global program around Data Governance as our data quality is shocking for a company of our size. Like most TA teams we are trying to figure out how best to utilize AI with tangible benefits and not just for show and tricks. High growth across multiple countries inc. lots of 1st in country hires in far off lands in MEA.",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "128491656706",
    "firstName": "Yuliia",
    "lastName": "Zembal",
    "jobTitle": "Head of Talent Acquisition ",
    "company": "UKRSIBBANK BNP PARIBAS GROUP ",
    "companySize": "100,000+",
    "industry": "Banking",
    "hiresPerYear": "1001-2000",
    "regionalRemit": "EMEA",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "AI implementation, process automation, IT employer Brand development, onboarding automation. ",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "I want to understand how can I implement AI instruments into TA processes in order to reduce time to hire and to save FTE. ",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "SHL",
    "ats": "Avature ",
    "crm": "SAP",
    "marketIntelligence": " -",
    "otherTools": "",
    "solutionAreas": "Onboarding automation, AI instruments in TA",
    "painPoints": "We are actively exploring vendors to implement AI instruments into TA processes but we should be very careful with the cybersecurity limitations. Also we are in the active stage of processes automation and looking for the instruments to improve experience on pre-onboarding and onboarding stages. We are exploring opportunities to improve time-to-hire of our mass positions in branches. ",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "122796319563",
    "firstName": "Julie",
    "lastName": "Lowe",
    "jobTitle": "Head of Talent Acquisition",
    "company": "easyJet",
    "companySize": "20,001-50,000",
    "industry": "Airlines/Aviation",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA",
    "decisionLevel": "Direct Approver",
    "activeProjects": "ATS replacement\nAssessments upgrade\nEngagement tool\nCRM",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "How do demonstrate ROI, What solutions are available, how to move from behind the curve to ahead. How to get AI into our process.",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "AON",
    "ats": "Taleo",
    "crm": "None",
    "marketIntelligence": "LinkedIn Talent Insights",
    "otherTools": "",
    "solutionAreas": "As above",
    "painPoints": "ATS not fit for purpose, no automated for screening high volumes of applicants (100k plus per year), out of date assessments, no CRM, unable to keep candidates engaged in hold pools.",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "174442448959",
    "firstName": "Joanna",
    "lastName": "Hackett",
    "jobTitle": "Group Talent Acquisition Excellence Lead",
    "company": "Howden",
    "companySize": "20,001-50,000",
    "industry": "Insurance",
    "hiresPerYear": "5001+",
    "regionalRemit": "EMEA,UK,LATAM,North America,UK&I,APAC,MENA,Other",
    "decisionLevel": "Direct Approver",
    "activeProjects": "MSP/SOW global; global workday and associates AI tech roll out; global onboarding optimisation;",
    "activeProjectBudget": "> £1m",
    "meetingObjective": "Reduced recruiter admin, better hiring manager and recruiter adoption, globally joined up systems  and data, global MSP to support with management of external workers, modular RPO to support with TA ecosystem optimisation, joined up global LMS",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "Arctic shores ",
    "ats": "Workday ",
    "crm": "TBc",
    "marketIntelligence": "TBC",
    "otherTools": "",
    "solutionAreas": "MSP/SOW vendor",
    "painPoints": "Agency usage, need for global MSP/SOW vendor, AI and automation, system standardisation; need for global CRM",
    "projectStage": "Planning & Budgeting (3-6 Months)"
  },
  {
    "id": "113145184682",
    "firstName": "Carly",
    "lastName": "George",
    "jobTitle": "Head of Talent Acquisition",
    "company": "AXA",
    "companySize": "100,000+",
    "industry": "Insurance",
    "hiresPerYear": "1001-2000",
    "regionalRemit": "UK,UK&I",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Automation, Sourcing Agent, Interview Scheduling, Talent Intelligence, ",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "Ultimately I'm looking for vendors who can bring insight , challenge and perspective, that can help to shape future capability, cut through complexity and demonstrate measurable impact, supporting new ways of working in an AI enabled world whilst striking the balance between innovation and governance",
    "budgetAuthority": "> £1m",
    "assessmentTools": "Korn Ferry, Arctic Shores",
    "ats": "ICIMS",
    "crm": "ICIMS",
    "marketIntelligence": "n/a",
    "otherTools": "",
    "solutionAreas": "Areas of interest include talent intelligence, advanced sourcing agents, skills based assessment methodology, executive assessment methodology, interview scheduling and coordination technology, enhanced data and analytics capability, VMS technology and Total Workforce Solutions",
    "painPoints": "Our TA function operates as an end to end enterprise model covering attraction, sourcing, assessment, selection and offer management across executive, specialist, volume, early careers and contingent recruitment. Having recently implemented a new ATS and CRM, with a new external careers site about to launch, we are now engaging the market to explore how our recruitment ecosystem can be optimised. ",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "111228357473",
    "firstName": "Hollie",
    "lastName": "Jordan",
    "jobTitle": "Head of Global Talent Acquisition",
    "company": "Ramboll",
    "companySize": "10,001-20,000",
    "industry": "Other",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA, North America, UK&I, APAC",
    "decisionLevel": "Direct Approver",
    "activeProjects": "Global Talent Acquisition Procedure & Governance, Pay Transparency Implementation, Hiring Manager Enablement, Global Leadership & Executive Hiring Transformation, Strategic Workforce Planning Integration, Nearshoring Centre Development (Europe), Early Careers Global Transformation, Employer Brand Activation.",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "Our HRIS is Workday, we previously had the Recruiting Module and then moved to SmartRecruiters. We're not sure if SR is a long term solution for us. We're open to moving from SHL in the next 12 months also.",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "SHL",
    "ats": "SmartRecruiters",
    "crm": "SmartRecruiters",
    "marketIntelligence": "LinkedIn Talent Insights previously, nothing today",
    "otherTools": "Datapeople",
    "solutionAreas": "Assessments",
    "painPoints": "Moving the business from “doing hiring” to trusting TA as the front door, consistency at global scale without losing local credibility, Hiring manager capability and accountability, leadership and executive hiring in a lean, risk-averse market, employer brand activation vs reality, strategic workforce planning that actually influences decisions and capacity vs ambition.",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "110260566550",
    "firstName": "Sonal",
    "lastName": "Jain",
    "jobTitle": "Global Head TA CoE",
    "company": "Nissan Motor Corporation",
    "companySize": "100,000+",
    "industry": "Automotive",
    "hiresPerYear": "5001+",
    "regionalRemit": "Other",
    "decisionLevel": "Key Influencer",
    "activeProjects": "Interview scheduling, WD integration, Screening tools",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "Interaction with other RL leaders",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "None",
    "ats": "Workday",
    "crm": "Workday",
    "marketIntelligence": "Linkedin",
    "otherTools": "",
    "solutionAreas": "Future of recruitment",
    "painPoints": "",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "191181142545",
    "firstName": "Christopher",
    "lastName": "Widdison",
    "jobTitle": "EMEA Head of Talent Acquisition",
    "company": "Macquarie",
    "companySize": "20,001-50,000",
    "industry": "Financial Services",
    "hiresPerYear": "251-500",
    "regionalRemit": "EMEA",
    "decisionLevel": "Key Influencer",
    "activeProjects": "Process optimisation, Speed of Hire, Reduction of Agency usage, Talent shortage, AI impact, DEI ",
    "activeProjectBudget": "£50-100k",
    "meetingObjective": "I am keen to understand what solutions are available to help tackle some of the key solution areas that are a priority for us. What solutions are available that require little integration to existing tech stacks",
    "budgetAuthority": "£50-100k",
    "assessmentTools": "Korn Ferry",
    "ats": "Avature",
    "crm": "Avature",
    "marketIntelligence": "LinkedIn",
    "otherTools": "",
    "solutionAreas": "Speed of hire - specifically niche front office roles, process consistency - specifically Interviews and assessment, Sourcing diverse talent, Market Insights - need to track key trends in the market and impact of AI",
    "painPoints": "",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "76678269091",
    "firstName": "Adam",
    "lastName": "Binks",
    "jobTitle": "Global Strategic Resourcing Lead",
    "company": "KPMG",
    "companySize": "100,000+",
    "industry": "Accounting",
    "hiresPerYear": "5001+",
    "regionalRemit": "Other",
    "decisionLevel": "Direct Approver",
    "activeProjects": "TA Credential programme, EVP refresh, Hiring manager enablement, AI use cases for TA",
    "activeProjectBudget": "£50-100k",
    "meetingObjective": "Global capability of vendors, ability to deploy as stand alone product and integrate with local ATSs but also have ability to consolidate into large enterprise HCM tools",
    "budgetAuthority": "£500K-£1m",
    "assessmentTools": "Various across our network",
    "ats": "Various- We have over 40 ATSs in our network, main vendor is SAP SF",
    "crm": "Various across our network",
    "marketIntelligence": "Various across our network including Phenom and Eightfold",
    "otherTools": "",
    "solutionAreas": "As above",
    "painPoints": "AI usage in TA across our member firm network, recruiter and hiring manager enablement, Recruiter training, EVP refresh.",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "17812226737",
    "firstName": "Rikki",
    "lastName": "Fullerton",
    "jobTitle": "Talent Acquisition Director",
    "company": "Serco",
    "companySize": "50,001-100,000",
    "industry": "Other",
    "hiresPerYear": "5001+",
    "regionalRemit": "UK,Other",
    "decisionLevel": "Key Influencer",
    "activeProjects": "Assessment, vetting & on-boarding ",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "I would like to get a better understanding of the latest capabilities (inc AI) of technology in the assessment, vetting & on-boarding space and the value they would bring to our organisation. ",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "AON",
    "ats": "Success Factors",
    "crm": "Phenom ",
    "marketIntelligence": "Talent Hub (SAP)",
    "otherTools": "",
    "solutionAreas": "Assessment, vetting, on-boarding",
    "painPoints": "We are currently reviewing how assessments can improve quality of hire and therefore reduce attrition, which is a strategic focus for Serco. I am also keen to look at technology in both vetting & on-boarding. We have a team of 40+ currently managing our vetting and on-boarding processes, and I am keen to introduce more advanced tech to improve efficiency and reduce processing time.",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "91889321035",
    "firstName": "Lucy",
    "lastName": "Bousfield",
    "jobTitle": "Global Head of talent Acquisition & Global Mobility",
    "company": "Aon",
    "companySize": "50,001-100,000",
    "industry": "Financial Services",
    "hiresPerYear": "5001+",
    "regionalRemit": "Other",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Assessment framework, Sourcing optimisation, Candidate experience",
    "activeProjectBudget": "£500k-£1m",
    "meetingObjective": "I want to connect to understand how others are navigating the everchanging talent landscape with AI solutions, digital transformation and optimisation of operating model.",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "AAS",
    "ats": "ICIMS",
    "crm": "ICIMS",
    "marketIntelligence": "Gartner and Linkedin",
    "otherTools": "",
    "solutionAreas": "Sourcing, employer brand, early careers, AI automation, talent intelligence",
    "painPoints": "Driving assessment strategy and framework, sourcing optimisation, early careers strategy impacted by AI and transformation, Implementating talent marketplace and skills based strategy",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "21545051",
    "firstName": "Jen",
    "lastName": "Hulme",
    "jobTitle": "Head of Talent Acquisition",
    "company": "BPP",
    "companySize": "2501-5000",
    "industry": "Education Management",
    "hiresPerYear": "501-1000",
    "regionalRemit": "EMEA, North America, UK&I, APAC",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Employer branding, workforce planning, systems integration",
    "activeProjectBudget": "£500k-£1m",
    "meetingObjective": "I want to understand how to build a global employer brand from scratch in an organisation with multiple subsidiaries. We are operating across different regions, cultures and levels of maturity, often following acquisition, and I need an approach that creates consistency and clarity without losing local identity.",
    "budgetAuthority": "< £50k",
    "assessmentTools": " -",
    "ats": "Tribepad",
    "crm": " -",
    "marketIntelligence": " -",
    "otherTools": "",
    "solutionAreas": "Employer branding agency",
    "painPoints": "I am working through a period of significant growth and change. We are acquiring two to three companies each year, mainly across APAC and North America, while continuing to grow organically in the UK and Europe.\n\nPost-merger integration is one of the biggest challenges. Each acquisition brings different systems, processes, data quality and ways of working. \n\nWorkforce planning is another key focus. We are rolling out a skills-based strategic workforce planning approach globally, moving away from traditional headcount models and matching skills to roles across very different markets and business models.\n\nEmployer branding is also a major piece of work. Following a global rebrand and new values and behaviours, we are effectively building a global employer brand from scratch and ensuring it lands consistently while still working locally.",
    "projectStage": "Planning & Budgeting (3-6 Months)"
  },
  {
    "id": "116903349643",
    "firstName": "James",
    "lastName": "Harley",
    "jobTitle": "Global Head of Executive Hiring",
    "company": "Syngenta",
    "companySize": "50,001-100,000",
    "industry": "Chemicals",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "Other",
    "decisionLevel": "Key Influencer",
    "activeProjects": "CRM for Exec level population, maturing the exec hiring function (following its creation in late 2024), developing sourcing capability globally",
    "activeProjectBudget": "> £1m",
    "meetingObjective": "I've had limited interaction with those that are leading Executive Hiring or have implemented a solution in this space since i took on this new role with Syngenta",
    "budgetAuthority": "£50-100k",
    "assessmentTools": "Hogan ",
    "ats": "Smart Recruiters ",
    "crm": "Smart Recruiters ",
    "marketIntelligence": "In-house - TalentNeuron, Seekout etc",
    "otherTools": "",
    "solutionAreas": "CRM, Market Intel & Insight",
    "painPoints": "Building a scalable Executive Hiring Function within in global business with consider needs in all regions.  We are aiming to balance building as a CoE but also impowering the regions to step up and hire at the senior end of our busines",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "16427701",
    "firstName": "Claudia",
    "lastName": "Sneddon Da Silva Raposo",
    "jobTitle": "Global HRIS DIrector and HRD UK NAM",
    "company": "Expleo Group",
    "companySize": "10,001-20,000",
    "industry": "Information Technology and Services",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "UK,North America",
    "decisionLevel": "Direct Approver",
    "activeProjects": "Review global ATS",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "Connect with likeminded people ",
    "budgetAuthority": "< £50k",
    "assessmentTools": "None",
    "ats": "iCIMS",
    "crm": "iCIMS LinkedIn",
    "marketIntelligence": "Oracle",
    "otherTools": "",
    "solutionAreas": "Competing with market salaries and our revenue",
    "painPoints": "",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "7258470500",
    "firstName": "Mark",
    "lastName": "Brooker",
    "jobTitle": "TA Director",
    "company": "BT Group",
    "companySize": "50,001-100,000",
    "industry": "Telecommunications",
    "hiresPerYear": "5001+",
    "regionalRemit": "UK, APAC",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Sourcing automation\nNew ATS\nOrg restructuring \nSkills hiring",
    "activeProjectBudget": "£500k-£1m",
    "meetingObjective": "Fresh thinking and networking",
    "budgetAuthority": "> £1m",
    "assessmentTools": "Sapia, SHL, Korn Ferry",
    "ats": "Success Factors",
    "crm": "N/A",
    "marketIntelligence": "Horsefly",
    "otherTools": "Topscore, Metaview, Real Links",
    "solutionAreas": "Agentic AI\nSourcing automation",
    "painPoints": "Reducing team budgets whilst not reducing quality; blending technology with human endeavour; skills based hiring",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "93380106578",
    "firstName": "Peter",
    "lastName": "Buchanan-Parker",
    "jobTitle": "Executive Director, Talent Acquisition",
    "company": "JPMorganChase",
    "companySize": "100,000+",
    "industry": "Financial Services",
    "hiresPerYear": "5001+",
    "regionalRemit": "EMEA,LATAM,North America,APAC,MENA",
    "decisionLevel": "Key Influencer",
    "activeProjects": "ATS\nAssessments\nCandidate Satisfaction",
    "activeProjectBudget": "> £1m",
    "meetingObjective": ".",
    "budgetAuthority": "< £50k",
    "assessmentTools": "mixed - HireVire",
    "ats": "Oracle Cloud",
    "crm": "Oracle Cloud",
    "marketIntelligence": "multiple",
    "otherTools": "",
    "solutionAreas": "above",
    "painPoints": "",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "191181016455",
    "firstName": "Nikhilesh",
    "lastName": "Mathur",
    "jobTitle": "nikhilesh.mathurlseg.com",
    "company": "London Stock Exchange Group",
    "companySize": "20,001-50,000",
    "industry": "Financial Services",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA,UK,LATAM,North America,UK&I,APAC,MENA,Other",
    "decisionLevel": "Key Influencer",
    "activeProjects": "Review Assessment Tools, Workday Adaptive, Hiredscore",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "Understand capability and cost of potential tools",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "Codility, Cappfinity",
    "ats": "Workday",
    "crm": "Beamery",
    "marketIntelligence": "LinkedIn Talent Insights",
    "otherTools": "",
    "solutionAreas": "Review Assessment Tools, Workday Adaptive, Hiredscore",
    "painPoints": "Reviewing assessment tools to funnel good quality candidates through the application process. Also reviewing tools to engage with passive candidates and bring them to the table for opportunistic discussions.",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "12731251",
    "firstName": "James",
    "lastName": "Boyle",
    "jobTitle": "Director of Global Associate Recruiting ",
    "company": "Latham & Watkins",
    "companySize": "5001-10,000",
    "industry": "Law Practice",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "Other",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "ATS, Employer Branding, AI ",
    "activeProjectBudget": "£500k-£1m",
    "meetingObjective": "I am responsible for building a best in class recruiting function with global cohesion and technology/ AI enabled. I also would like to enhance our brand and meet with other global TA leaders on how they are thinking about the evolution of the function. ",
    "budgetAuthority": "£500K-£1m",
    "assessmentTools": "Cappfinity",
    "ats": "iCIMS",
    "crm": "iCIMS",
    "marketIntelligence": "Pirical, Leopard, Firm Prospects ",
    "otherTools": "",
    "solutionAreas": "AI ",
    "painPoints": "Assessment & Selection, AI add on to ATS, Employer branding/ activation specialists globally. ",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "91862577670",
    "firstName": "Lisa",
    "lastName": "Brignall",
    "jobTitle": "Head of TA, GB",
    "company": "Coca-Cola Europacific partners",
    "companySize": "20,001-50,000",
    "industry": "Consumer Goods",
    "hiresPerYear": "1001-2000",
    "regionalRemit": "UK",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Technology and process optimisation; employer branding and skills based hiring (capabilities and embedding)",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "I want to learn more about tech out there that can support overall goals to optimise processes; particularly interested in programmatic, AI developments for sourcing; employer branding and data sources; id  like to share and understand key trends in the market and take the opportunity to learn across and build networks. ",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "Talogy",
    "ats": "Successfactors",
    "crm": "Eightfold",
    "marketIntelligence": "Horsefly",
    "otherTools": "",
    "solutionAreas": "Programmatic and AI enabled tech.",
    "painPoints": "Evolving the TA function to be more proactive and strategic, Humanising AI in processes; inclusive hiring. Evolving capabilities of teams. ",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "9477501",
    "firstName": "Edwin",
    "lastName": "Pene",
    "jobTitle": "Global Head of TA Operations",
    "company": "Red Bull",
    "companySize": "20,001-50,000",
    "industry": "Food & Beverages",
    "hiresPerYear": "5001+",
    "regionalRemit": "EMEA,LATAM,North America,APAC,MENA",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Early Careers process review, Hiring for Growth, Elevating Selection",
    "activeProjectBudget": "£500k-£1m",
    "meetingObjective": "Within our ecosystem, SmartRecruiters, what are some of the technologies that could help us with the volume of applications, so recruiters concentrate on the few good candidates, which ultimately should help in hiring faster without compromising the quality. They would need to fully integrate with SmartRecruiters, as we believe in a single source of truth and consolidated data reporting. ",
    "budgetAuthority": "£50-100k",
    "assessmentTools": "HireVue, Red Bull Wingfinder, PillarHR",
    "ats": "SmartRecruiters",
    "crm": "SmartRecruiters",
    "marketIntelligence": "LinkedIn Talent Insights",
    "otherTools": "",
    "solutionAreas": "AI Screening (Top funnel), On-demand interview (High Volume Assessment), Ai Noteraker",
    "painPoints": "Reduce time-to-hire without compromising quality of hire.  Hiring volume is one of the challenges; we have a high number of applicants (1000+), so how do we get to the few good profiles at the top of the funnel, while ensuring a positive candidate experience. \n\nOn a similar line, high-volume assessments for Early Careers and Sales roles.\n\nGet Hiring Managers to focus on interviewing with our framework and methods, without worrying about taking notes during interviews, and upskill them through coaching. ",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "8952301",
    "firstName": "Chris",
    "lastName": "Tennant",
    "jobTitle": "VP Talent Acquisition",
    "company": "Infor",
    "companySize": "10,001-20,000",
    "industry": "Computer Software",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA,UK,LATAM,North America,UK&I,APAC,MENA",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Implementation of ATS, Onboarding. ",
    "activeProjectBudget": "< £50k",
    "meetingObjective": "Gain a deeper knowledge of what I would need coming up",
    "budgetAuthority": "£100-500k",
    "assessmentTools": "None",
    "ats": "Pinpoint from June",
    "crm": "Pinpoint from June",
    "marketIntelligence": "None",
    "otherTools": "",
    "solutionAreas": "Would be interested in background checking vendors",
    "painPoints": "Metrics will be improving and so will my effeciencies with the new ATS. Challenege will be how to scale the team to be more consultative",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "8713772",
    "firstName": "Alan",
    "lastName": "MacKinnon",
    "jobTitle": "Senior Director of TA (EMEA and APAC)",
    "company": "Smith and Nephew plc",
    "companySize": "10,001-20,000",
    "industry": "Medical Devices",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA,APAC",
    "decisionLevel": "Key Influencer",
    "activeProjects": "Background Checks\nContingent worker RPO and MSP\nSelection and assessment technology\nHiring Manager and end users education & support",
    "activeProjectBudget": "£500k-£1m",
    "meetingObjective": "Better understanding of how the solutions 'are better' than existing partnerships/solutions ; Approaches to implementation, adoption and realization of benefits",
    "budgetAuthority": "< £50k",
    "assessmentTools": "SHL",
    "ats": "Workday",
    "crm": "Workday CE",
    "marketIntelligence": "Talent Neuron",
    "otherTools": "",
    "solutionAreas": "Contingent worker RPO",
    "painPoints": "Balancing global consistency with regional relevance (legal, cultural, language etc) ; driving positive process and tech adoption across users and stakeholders ; Fully capitalizing on the benefits of Tech, AI & Automation while protecting the human experience of recruitment",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "192905181704",
    "firstName": "Theresa",
    "lastName": "O'Brien",
    "jobTitle": "Global Head of Talent Acquisition",
    "company": "CBRE",
    "companySize": "100,000+",
    "industry": "Facilities Services",
    "hiresPerYear": "5001+",
    "regionalRemit": "Other",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Assessment & Selection refresh\nHiring manager recruitment & selection training \n5 year workforce plan",
    "activeProjectBudget": "£50-100k",
    "meetingObjective": "I want to identify best assessment & selection solutions for hiring for future needs",
    "budgetAuthority": "> £1m",
    "assessmentTools": "SHL & Thomas international",
    "ats": "Avature",
    "crm": "Avature",
    "marketIntelligence": "NA",
    "otherTools": "",
    "solutionAreas": "Assessment & selection",
    "painPoints": "Scaling volume hiring at pace in countries without dedicated TA support\nEnsuring quality leadership hiring in fast paced candidate short markets\nRefreshing selection & psychometrics tools to meet future hiring needs",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "8196151",
    "firstName": "Michelle",
    "lastName": "Monahan",
    "jobTitle": "Head of Recruitment",
    "company": "European Tyre Enterprise Limited",
    "companySize": "5001-10,000",
    "industry": "Automotive",
    "hiresPerYear": "1001-2000",
    "regionalRemit": "UK&I",
    "decisionLevel": "Key Influencer",
    "activeProjects": "1. Automation\n2.Have a 100 MOT roles coming down the line (additional headcount, there is a massive skills shortage in the Automotive Industry and MOT tester are like unicorns, our pay is average and the market highly competitive\n3.  From approx June I will get the go ahead to start advertising and will need to recruit 300 Apprentices 16-18 year olds to start between Sept and Nov.  Conscious will miss the school leavers who start looking from April onwards.  This a mammoth task, we normally recruit 300 apprentices across the year with a team of 2 recruiters and receive approx 18,000 applications, so conscious this is going to be condensed in to a small time frame.  How do manage that volume, deliver the result whilst ensuring candidate experience isn't impacted.\n4. Upskilling/team development.  Scared of technology, how I help, support and train.\n5.  Background checks for keys roles for Finance etc.",
    "activeProjectBudget": "< £50k",
    "meetingObjective": "What systems/software that are compatible and cost effective that can help me support with current projects and deliver what I need to the business that helps and supports the team to make us more efficient",
    "budgetAuthority": "< £50k",
    "assessmentTools": "we don't have one",
    "ats": "TalentLink",
    "crm": "we don't have one",
    "marketIntelligence": "we don't have one",
    "otherTools": "",
    "solutionAreas": "Anything that can help me with the above",
    "painPoints": "1. What I can automate in candidate process, without losing the human touch and missing out on talent, to ensure team is most productive and do what they do best.  This is more so for unskilled roles where attitude prevails over experience and where our highest volume of recruitment comes from.  Doing more with less headcount.",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "11132851",
    "firstName": "Martin",
    "lastName": "McDermott",
    "jobTitle": "Global Director of Talent Acquisition ",
    "company": "IQ-EQ",
    "companySize": "5001-10,000",
    "industry": "Financial Services",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA,North America,APAC",
    "decisionLevel": "Direct Approver",
    "activeProjects": "Adoption of Winston AI from Smart Recruiters in our tech stack, Onboarding portal solutions to go from hiring decision to candidate acceptance quickly ",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "We need to focus on technology that directly addresses our current challenges and can automate key stages of the end to end recruitment journey. Over the next two years we expect to explore the adoption of a global ERP, so our approach must balance both short term needs and longer term direction. In the short term, we require a solution that simplifies the hiring process and enhances the experience for candidates and hiring managers. Longer term, we will need a stronger user experience layer to complement the core ERP, recognising that major ERP vendors have not yet fully addressed the experience gaps that exist across the recruitment journey.",
    "budgetAuthority": "£500K-£1m",
    "assessmentTools": "Hogan at leadership, Aon ",
    "ats": "Smart Recruiters",
    "crm": "HireEZ",
    "marketIntelligence": "None",
    "otherTools": "",
    "solutionAreas": "CRM and Onboarding Solution tech to support top of the funnell",
    "painPoints": "As we shift from a reactive Talent Acquisition model to an always on hiring approach, several challenges are limiting our ability to move quickly from hiring demand to shortlist to start date.\nHiring demand often reaches TA too late.\nThe business frequently signals resource needs only at the point of urgency. This compresses timelines, restricts our ability to pipeline, and forces reactive sourcing that slows down delivery.\nWe lack consistent, structured talent pipelines.\nSustained talent pools for repeatable and high volume roles are not yet embedded across our global function. Without active pipelines, creating a high quality shortlist takes significantly longer.\nProcesses and tools are creating friction instead of reducing it.\nOur workflows still include multiple handoffs, manual steps, and inconsistent adoption of platforms. These bottlenecks slow feedback, extend decision making, and create unnecessary delays throughout the hiring process.\nHiring manager readiness and expectations vary.\nDifferences in role scoping, interview capability, and feedback turnaround lead to avoidable delays. Where managers lack clarity or support, the hiring journey becomes slower and more complex.\nThe candidate experience is not designed for pace.\nSlow communication, long interview cycles, and inconsistent touchpoints negatively impact engagement. In competitive markets, this leads to candidate withdrawals and missed hiring opportunities.\nData is not yet predictive or operational.\nWhile we collect activity data, we do not have real time insights that forecast demand, highlight bottlenecks, or assess pipeline health. This keeps TA in a reactive posture rather than enabling proactive intervention.",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "92953690026",
    "firstName": "Oliver",
    "lastName": "Browne",
    "jobTitle": "Global Head of Talent Acquisition",
    "company": "Lockton",
    "companySize": "10,001-20,000",
    "industry": "Insurance",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA, LATAM, UK, North America, UK&I, APAC, MENA",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Talent Marketing, Talent Intelligence and Global Technology implementation and change",
    "activeProjectBudget": "> £1m",
    "meetingObjective": "Networking with like minded people with global knowledge",
    "budgetAuthority": "> £1m",
    "assessmentTools": "SHL",
    "ats": "People soft",
    "crm": "None",
    "marketIntelligence": "Building",
    "otherTools": "LinkedIn, US Sourcing tools, Handshake etc",
    "solutionAreas": "Talent Intelligence",
    "painPoints": "Tech Implementation and Global TA Transformation",
    "projectStage": "Planning & Budgeting (3-6 Months)"
  },
  {
    "id": "4956154",
    "firstName": "Jules",
    "lastName": "Anderson",
    "jobTitle": "Senior Director, Talent Acquisition and Global Mobility",
    "company": "Gilead Science",
    "companySize": "10,001-20,000",
    "industry": "Biotechnology",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "Other",
    "decisionLevel": "Direct Approver",
    "activeProjects": "New CRM and candidate experience tech system and AI enabled screening tool + new EVP",
    "activeProjectBudget": "> £1m",
    "meetingObjective": "AI enabled tech, candidate experience, recruiter efficiency, talen development and internal mobility.",
    "budgetAuthority": "> £1m",
    "assessmentTools": "None",
    "ats": "Workday",
    "crm": "Yello (terrible needs to be replaced, good for event management)",
    "marketIntelligence": "Linked In recruiter",
    "otherTools": "",
    "solutionAreas": "As above - both but for the tech vendor support specifically mid 2026.",
    "painPoints": "Candidate Screening, Internal Mobility, talent development within TA, collaboration and engagement, candidate experience, employer branding",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "190937723960",
    "firstName": "Natalie",
    "lastName": "McGuinness",
    "jobTitle": "Head of Talent Acquisition ",
    "company": "Busy Bees Nurseries",
    "companySize": "10,001-20,000",
    "industry": "Primary/Secondary Education",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "UK&I",
    "decisionLevel": "Key Influencer",
    "activeProjects": "AI selection tools, MSP platform, Candidate experience, Talent pipe lining",
    "activeProjectBudget": "< £50k",
    "meetingObjective": "I want to be really clear on where AI adds value to a TA related activity and how to risk assess before creating a business case ",
    "budgetAuthority": "< £50k",
    "assessmentTools": "N/A",
    "ats": "iCIMS",
    "crm": "N/a",
    "marketIntelligence": "N/a",
    "otherTools": "",
    "solutionAreas": "AI solutions ",
    "painPoints": "Volume/quality ",
    "projectStage": "Planning & Budgeting (3-6 Months)"
  },
  {
    "id": "5140258",
    "firstName": "Sarah",
    "lastName": "Cooper",
    "jobTitle": "Group HR Technology, Insights and Recruitment Director",
    "company": "Rentokil Initial",
    "companySize": "50,001-100,000",
    "industry": "Other",
    "hiresPerYear": "5001+",
    "regionalRemit": "EMEA, UK, LATAM, North America, UK&I, APAC, MENA",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "ATS\nSkills Assessment\nCareersite enhancement",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "To see how I can pilot and scale across a challenging devolved tech stack. To either enhance Workday or to use an alternative ATS with solid global language offerings",
    "budgetAuthority": "£500K-£1m",
    "assessmentTools": "Vervoe",
    "ats": "Workable, Workday and SmartRecruiters",
    "crm": "Recruitment Smart",
    "marketIntelligence": "Linkedin",
    "otherTools": "",
    "solutionAreas": "ATS\nSkills Assessment\nCareersite enhancement",
    "painPoints": "ATS",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "91862579761",
    "firstName": "Laura",
    "lastName": "Callaghan",
    "jobTitle": "Global Talent Acquisition Leader",
    "company": "Western Union",
    "companySize": "5001-10,000",
    "industry": "Financial Services",
    "hiresPerYear": "1001-2000",
    "regionalRemit": "EMEA, APAC",
    "decisionLevel": "Key Influencer",
    "activeProjects": "Integration of new acquisitions\nInternal mobility\nOnboarding",
    "activeProjectBudget": "< £50k",
    "meetingObjective": "TBC",
    "budgetAuthority": "< £50k",
    "assessmentTools": "Criteria",
    "ats": "Workday",
    "crm": "NA",
    "marketIntelligence": "Talent insights",
    "otherTools": "Paradox",
    "solutionAreas": "Candidate screening at application",
    "painPoints": "Candidate screening at application\nCollection of interview notes",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "910801",
    "firstName": "Caroline",
    "lastName": "Loubert",
    "jobTitle": "Global Head of TA",
    "company": "Argus Media Ltd",
    "companySize": "1001-2500",
    "industry": "Information Services",
    "hiresPerYear": "251-500",
    "regionalRemit": "EMEA, UK, LATAM, North America, APAC, MENA",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Integrate ATS with HRIS, Introduce a new scheduling tool, globalise recruitment process, automate processes and bring in AI, automate reporting.",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "I have 20 years plus recruitment experience and I have been with Argus for 8 years in that time we have grown from 800 employees to 1600 employees, I have implemented a new ATS and grown the TA function from 1 to 8 in this time, however I really would like the toolkit now to navigate the next stages of my career with more C level reporting and bringing new ideas to the function",
    "budgetAuthority": "< £50k",
    "assessmentTools": "Predictive Index",
    "ats": "Teamtailor",
    "crm": "Salesforce",
    "marketIntelligence": "LinkedIn",
    "otherTools": "HRIS - Workday",
    "solutionAreas": "Talent Sourcing, Employee Branding and Automated testing tools.",
    "painPoints": "I have 20 years plus recruitment experience and I have been with Argus for 8 years in that time we have grown from 800 employees to 1600 employees, I have implemented a new ATS and grown the TA function from 1 to 8 in this time, however I really would like the toolkit now to navigate the next stages of my career with more C level reporting and bringing new ideas to the function",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "9322701",
    "firstName": "Tush",
    "lastName": "Wijeratne",
    "jobTitle": "Global Director of Talent Acquisition",
    "company": "WPP",
    "companySize": "100,000+",
    "industry": "Marketing and Advertising",
    "hiresPerYear": "1001-2000",
    "regionalRemit": "EMEA, North America, UK&I, APAC, Other",
    "decisionLevel": "Key Influencer",
    "activeProjects": "Offshore souring hubs / tooling - India \nLinkedIn alternatives\nAI usage identification tools in tech tests and interviews",
    "activeProjectBudget": "< £50k",
    "meetingObjective": "Keen to understand the leading industry techniques and tools which should be recommended for the future of talent acquisition at WPP as we gorgeous a global transformation. I am awaiting the new CEO’s vision and this should then help with future TA transformation and relevant budgets.",
    "budgetAuthority": "< £50k",
    "assessmentTools": "N/A",
    "ats": "Greenhouse",
    "crm": "Greenhouse",
    "marketIntelligence": "Talent Neuron",
    "otherTools": "LinkedIn and Hireze",
    "solutionAreas": "AI usage identification",
    "painPoints": "Offshoring and restructure of TA",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "93174643474",
    "firstName": "Salina",
    "lastName": "Budaly",
    "jobTitle": "Global TA Leader ",
    "company": "Balfour Beatty",
    "companySize": "1001-2500",
    "industry": "Construction",
    "hiresPerYear": "1001-2000",
    "regionalRemit": "UK&I",
    "decisionLevel": "Direct Approver",
    "activeProjects": "AI, ATS EVP ",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "I would like to explore vendors to support a TA transformation ",
    "budgetAuthority": "£500K-£1m",
    "assessmentTools": "None ",
    "ats": "Talent Link",
    "crm": "Beamary ",
    "marketIntelligence": "LinkedIn Insights ",
    "otherTools": "",
    "solutionAreas": "Talent Insight, EVP",
    "painPoints": "Cost per application volume applications quality candidates",
    "projectStage": "Actively Evaluating Vendors"
  },
  {
    "id": "93137898669",
    "firstName": "Jennifer",
    "lastName": "Cunningham",
    "jobTitle": "Vice president global recruiting",
    "company": "Pearson",
    "companySize": "10,001-20,000",
    "industry": "Education Management",
    "hiresPerYear": "5001+",
    "regionalRemit": "EMEA, LATAM, North America, UK&I, APAC, MENA",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Background Vendor Selection. Assessment Selection, Automation",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "understanding solutions and best practice on the challenges outlined above",
    "budgetAuthority": "> £1m",
    "assessmentTools": "Gallup, Codility",
    "ats": "Oracle",
    "crm": "none",
    "marketIntelligence": "Talent Insights and internal People analytics team",
    "otherTools": "SnOW, CoPilot Studio, Fathem & Credly",
    "solutionAreas": "Weeding out and assessing for fakes in SW engineering specifically",
    "painPoints": "Rise of AI generated applications and Fake profiles driving TTH up while increasing recruiter frustrations. Supply and demand of Technology candidates and the need to be more creative on approach. Diversification of Geo's creating extra complexities on administration resource. Ai and automation as a User case. Need for validated and robust Assessment and selection  tools",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "92353346050",
    "firstName": "Debbie",
    "lastName": "Robinson",
    "jobTitle": "TA COE Strategy Lead",
    "company": "PepsiCo",
    "companySize": "100,000+",
    "industry": "Food Production",
    "hiresPerYear": "5001+",
    "regionalRemit": "EMEA, Other",
    "decisionLevel": "Key Influencer",
    "activeProjects": "Front Line ATS solution but vendor is selected (Paradox)",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "Understanding",
    "budgetAuthority": "£50-100k",
    "assessmentTools": "Inhouse - PEPhire",
    "ats": "iCIMS",
    "crm": "iCIMS",
    "marketIntelligence": "Draup, LinkedIn Talent Insights, Talent Neuron.",
    "otherTools": "Pillar",
    "solutionAreas": "Early Talent, Assessment",
    "painPoints": "We're focused on optimizing current solutions.  We are working on Global Early Talent and I don't think iCIMS is the solution for this.  I would also question whether our assessment solutions are fit for purpose.  I can influence but I'm not a decision maker on the technologies we choose - these decision are made from New York.",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "13454401",
    "firstName": "Mark",
    "lastName": "Coad",
    "jobTitle": "Director, Talent Acquisition Transformation ",
    "company": "GSK",
    "companySize": "50,001-100,000",
    "industry": "Pharmaceuticals",
    "hiresPerYear": "5001+",
    "regionalRemit": "Other",
    "decisionLevel": "Direct Approver",
    "activeProjects": "CRM launch, Agentic AI, offshoring",
    "activeProjectBudget": "> £1m",
    "meetingObjective": "Sharing and learning from peers on their journey.",
    "budgetAuthority": "> £1m",
    "assessmentTools": "SHL",
    "ats": "Workday",
    "crm": "Phenom",
    "marketIntelligence": "LinkedIn",
    "otherTools": "",
    "solutionAreas": "Translation services, RPO, AI",
    "painPoints": "Delivering financial savings via simplification, AI embedment and offshoring is challenging whilst delivering consistent service experience.  ",
    "projectStage": "Planning & Budgeting (3-6 Months)"
  },
  {
    "id": "1076201",
    "firstName": "Jon",
    "lastName": "Warwick",
    "jobTitle": "Group Director TA",
    "company": "Sky",
    "companySize": "20,001-50,000",
    "industry": "Broadcast Media",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "EMEA",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "Assessment Tech, RPO renewal, AI",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "Networking with peers and sharing ideas on future focus.",
    "budgetAuthority": "> £1m",
    "assessmentTools": "Sova, SHL, Cappfinity, Codility",
    "ats": "Workday",
    "crm": "TUX",
    "marketIntelligence": "Horesfly",
    "otherTools": "",
    "solutionAreas": "AI, Assessment tech, Talent Marketplace, Skills",
    "painPoints": "",
    "projectStage": "Planning & Budgeting (3-6 Months)"
  },
  {
    "id": "452351",
    "firstName": "Cath",
    "lastName": "Possamai",
    "jobTitle": "TA Director",
    "company": "Amazon",
    "companySize": "100,000+",
    "industry": "Retail",
    "hiresPerYear": "5001+",
    "regionalRemit": "EMEA, MENA",
    "decisionLevel": "Final Budget Holder",
    "activeProjects": "see above",
    "activeProjectBudget": "> £1m",
    "meetingObjective": "Networking with peers - understand how they are approaching similar challenges. Insight into what tech vendors are offering to inform our own roadmap (you might not like to read this but at least I am honest!)",
    "budgetAuthority": "> £1m",
    "assessmentTools": "All bespoke, in house",
    "ats": "HIRE (bespoke, in house)",
    "crm": "HIRE (bespoke, in house)",
    "marketIntelligence": "In house",
    "otherTools": "",
    "solutionAreas": "See above",
    "painPoints": "Improve Quality of Hire; Precision at scale in selection and assessment; standardisation of process and roles across a huge global TA team; agile and data led capacity sharing; demand planning. BUT - we build ALL our tech in house so although I am interested in what is out there I am really unlikely to buy anything!",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  },
  {
    "id": "150796696175",
    "firstName": "Jennifer",
    "lastName": "Candee",
    "jobTitle": "Global VP TA",
    "company": "Prior IMI, Cargill, Mondelez ",
    "companySize": "10,001-20,000",
    "industry": "Mechanical or Industrial Engineering",
    "hiresPerYear": "2001-5000",
    "regionalRemit": "Other",
    "decisionLevel": "Key Influencer",
    "activeProjects": "TBC. In between roles ",
    "activeProjectBudget": "£100-500k",
    "meetingObjective": "Interviewing now for global vp ta roles both consultancy and perm. Look to multinational ai solutions integrate well into global enterprise ats ",
    "budgetAuthority": "£50-100k",
    "assessmentTools": "TBC ",
    "ats": "TBC ",
    "crm": "TBC ",
    "marketIntelligence": "TBC ",
    "otherTools": "",
    "solutionAreas": "TBC ",
    "painPoints": "TBC based on new contract or perm role ",
    "projectStage": "Benchmarking for Future Use (6-12 Months)"
  }
];
