export interface Attendee {
  id: string;
  firstName: string;
  lastName: string;
  jobTitle: string;
  company: string;
  companySize: string;
  industry: string;
  teamSize: string;
  budgetAuthority: string;
  assessmentTool: string;
  ats: string;
  crm: string;
  marketIntelligence: string;
  otherTools: string;
}

export const attendees: Attendee[] = [
  {
    id: "200923910443",
    firstName: "Nuria",
    lastName: "Munoz",
    jobTitle: "Head of Talent Acquisition Europe and Latin America",
    company: "Munich Re",
    companySize: "50,001-100,000",
    industry: "Insurance",
    teamSize: "2001-5000",
    budgetAuthority: "Direct Approver",
    assessmentTool: "Various vendors across the world, non consistent",
    ats: "Success Factors",
    crm: "None",
    marketIntelligence: "Cobrainer",
    otherTools: ""
  },
  {
    id: "200101377371",
    firstName: "Jessica Shaunie",
    lastName: "Green",
    jobTitle: "Head of talent acquisition",
    company: "Calor gas",
    companySize: "5001-10,000",
    industry: "Oil & Energy",
    teamSize: "1001-2000",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "Korn ferry",
    ats: "Workday",
    crm: "Pageup",
    marketIntelligence: "N/a",
    otherTools: ""
  },
  {
    id: "195183358360",
    firstName: "Anna",
    lastName: "Katyal",
    jobTitle: "Head of Talent Acquisition",
    company: "BMS Group",
    companySize: "1001-2500",
    industry: "Insurance",
    teamSize: "251-500",
    budgetAuthority: "Key Influencer",
    assessmentTool: "N/A",
    ats: "N/A",
    crm: "N/A",
    marketIntelligence: "N/A",
    otherTools: ""
  },
  {
    id: "194698768792",
    firstName: "Nainik",
    lastName: "Patel",
    jobTitle: "Delivery Lead, Head of Global Talent Acquisition",
    company: "Hitachi",
    companySize: "100,000+",
    industry: "Information Technology and Services",
    teamSize: "2001-5000",
    budgetAuthority: "Direct Approver",
    assessmentTool: "…",
    ats: "Workday",
    crm: "…",
    marketIntelligence: "…",
    otherTools: ""
  },
  {
    id: "194295425320",
    firstName: "Robyn",
    lastName: "Collins",
    jobTitle: "VP TA",
    company: "M42",
    companySize: "20,001-50,000",
    industry: "Hospital & Health Care",
    teamSize: "2001-5000",
    budgetAuthority: "Direct Approver",
    assessmentTool: "Building a global bank of assessments by function and level",
    ats: "iCIMS and Success Factors",
    crm: "iCIMS Jibe",
    marketIntelligence: "NIL",
    otherTools: ""
  },
  {
    id: "192303904943",
    firstName: "joanna",
    lastName: "saunders-hare",
    jobTitle: "Executive Director, Talent Acquisition",
    company: "MUFG, Mitsubishi UFJ Financial Group.",
    companySize: "1001-2500",
    industry: "Financial Services",
    teamSize: "1001-2000",
    budgetAuthority: "Direct Approver",
    assessmentTool: "Assess Candidates",
    ats: "Smart Recruiters",
    crm: "Smart Recruiters",
    marketIntelligence: "LinkedIn Insights",
    otherTools: ""
  },
  {
    id: "190898269597",
    firstName: "Jonathan",
    lastName: "Kitterhing best",
    jobTitle: "Global head of Talent Acquisition",
    company: "Swiss Re Management Ltd",
    companySize: "10,001-20,000",
    industry: "Insurance",
    teamSize: "2001-5000",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "RR bespoke, Hogan, SHL",
    ats: "SAP SSF",
    crm: "Phenom",
    marketIntelligence: "SSF module",
    otherTools: "IN house built Textio type tool, Talent Neuron, LI Insights, Social Talent"
  },
  {
    id: "185464523694",
    firstName: "David",
    lastName: "Nottage",
    jobTitle: "Head of TA",
    company: "Screwfix",
    companySize: "10,001-20,000",
    industry: "Retail",
    teamSize: "2001-5000",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "Multiple",
    ats: "iCIMS",
    crm: "SAP",
    marketIntelligence: "N/A",
    otherTools: "Various, but nothing outstanding"
  },
  {
    id: "183232510638",
    firstName: "James",
    lastName: "Kennedy",
    jobTitle: "Talent Acquisition Director, EMEA",
    company: "Palo Alto Networks",
    companySize: "10,001-20,000",
    industry: "Information Technology and Services",
    teamSize: "501-1000",
    budgetAuthority: "Direct Approver",
    assessmentTool: "HiredScore",
    ats: "Workday",
    crm: "Workday",
    marketIntelligence: "None",
    otherTools: "Paradox"
  },
  {
    id: "128491656706",
    firstName: "Yuliia",
    lastName: "Zembal",
    jobTitle: "Head of Talent Acquisition",
    company: "UKRSIBBANK BNP PARIBAS GROUP",
    companySize: "100,000+",
    industry: "Banking",
    teamSize: "1001-2000",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "SHL",
    ats: "Avature",
    crm: "SAP",
    marketIntelligence: "-",
    otherTools: ""
  },
  {
    id: "191166947669",
    firstName: "James",
    lastName: "Stirling",
    jobTitle: "Senior Director, Talent Acquisition",
    company: "Marriott International",
    companySize: "100,000+",
    industry: "Hospitality",
    teamSize: "5001+",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "Aon - Managed by US and out of scope",
    ats: "Oracle - Taleo",
    crm: "None",
    marketIntelligence: "LinkedIn",
    otherTools: ""
  },
  {
    id: "122796319563",
    firstName: "Julie",
    lastName: "Lowe",
    jobTitle: "Head of Talent Acquisition",
    company: "easyJet",
    companySize: "20,001-50,000",
    industry: "Airlines/Aviation",
    teamSize: "2001-5000",
    budgetAuthority: "Direct Approver",
    assessmentTool: "AON",
    ats: "Taleo",
    crm: "None",
    marketIntelligence: "LinkedIn Talent Insights",
    otherTools: ""
  },
  {
    id: "174442448959",
    firstName: "Joanna",
    lastName: "Hackett",
    jobTitle: "Group Talent Acquisition Excellence Lead",
    company: "Howden",
    companySize: "20,001-50,000",
    industry: "Insurance",
    teamSize: "5001+",
    budgetAuthority: "Direct Approver",
    assessmentTool: "Arctic shores",
    ats: "Workday",
    crm: "TBc",
    marketIntelligence: "TBC",
    otherTools: ""
  },
  {
    id: "113145184682",
    firstName: "Carly",
    lastName: "George",
    jobTitle: "Head of Talent Acquisition",
    company: "AXA",
    companySize: "100,000+",
    industry: "Insurance",
    teamSize: "1001-2000",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "Korn Ferry, Arctic Shores",
    ats: "ICIMS",
    crm: "ICIMS",
    marketIntelligence: "n/a",
    otherTools: ""
  },
  {
    id: "111228357473",
    firstName: "Hollie",
    lastName: "Jordan",
    jobTitle: "Head of Global Talent Acquisition",
    company: "Ramboll",
    companySize: "10,001-20,000",
    industry: "Other",
    teamSize: "2001-5000",
    budgetAuthority: "Direct Approver",
    assessmentTool: "SHL",
    ats: "SmartRecruiters",
    crm: "SmartRecruiters",
    marketIntelligence: "LinkedIn Talent Insights previously, nothing today",
    otherTools: "Datapeople"
  },
  {
    id: "110260566550",
    firstName: "Sonal",
    lastName: "Jain",
    jobTitle: "Global Head TA CoE",
    company: "Nissan Motor Corporation",
    companySize: "100,000+",
    industry: "Automotive",
    teamSize: "5001+",
    budgetAuthority: "Key Influencer",
    assessmentTool: "None",
    ats: "Workday",
    crm: "Workday",
    marketIntelligence: "Linkedin",
    otherTools: ""
  },
  {
    id: "191181142545",
    firstName: "Christopher",
    lastName: "Widdison",
    jobTitle: "EMEA Head of Talent Acquisition",
    company: "Macquarie",
    companySize: "20,001-50,000",
    industry: "Financial Services",
    teamSize: "251-500",
    budgetAuthority: "Key Influencer",
    assessmentTool: "Korn Ferry",
    ats: "Avature",
    crm: "Avature",
    marketIntelligence: "LinkedIn",
    otherTools: ""
  },
  {
    id: "76678269091",
    firstName: "Adam",
    lastName: "Binks",
    jobTitle: "Global Strategic Resourcing Lead",
    company: "KPMG",
    companySize: "100,000+",
    industry: "Accounting",
    teamSize: "5001+",
    budgetAuthority: "Direct Approver",
    assessmentTool: "Various across our network",
    ats: "Various- We have over 40 ATSs in our network, main vendor is SAP SF",
    crm: "Various across our network",
    marketIntelligence: "Various across our network including Phenom and Eightfold",
    otherTools: ""
  },
  {
    id: "17812226737",
    firstName: "Rikki",
    lastName: "Fullerton",
    jobTitle: "Talent Acquisition Director",
    company: "Serco",
    companySize: "50,001-100,000",
    industry: "Other",
    teamSize: "5001+",
    budgetAuthority: "Key Influencer",
    assessmentTool: "AON",
    ats: "Success Factors",
    crm: "Phenom",
    marketIntelligence: "Talent Hub (SAP)",
    otherTools: ""
  },
  {
    id: "91889321035",
    firstName: "Lucy",
    lastName: "Bousfield",
    jobTitle: "Global Head of talent Acquisition & Global Mobility",
    company: "Aon",
    companySize: "50,001-100,000",
    industry: "Financial Services",
    teamSize: "5001+",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "AAS",
    ats: "ICIMS",
    crm: "ICIMS",
    marketIntelligence: "Gartner and Linkedin",
    otherTools: ""
  },
  {
    id: "21545051",
    firstName: "Jen",
    lastName: "Hulme",
    jobTitle: "Head of Talent Acquisition",
    company: "BPP",
    companySize: "2501-5000",
    industry: "Education Management",
    teamSize: "501-1000",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "-",
    ats: "Tribepad",
    crm: "-",
    marketIntelligence: "-",
    otherTools: ""
  },
  {
    id: "116903349643",
    firstName: "James",
    lastName: "Harley",
    jobTitle: "Global Head of Executive Hiring",
    company: "Syngenta",
    companySize: "50,001-100,000",
    industry: "Chemicals",
    teamSize: "2001-5000",
    budgetAuthority: "Key Influencer",
    assessmentTool: "Hogan",
    ats: "Smart Recruiters",
    crm: "Smart Recruiters",
    marketIntelligence: "In-house - TalentNeuron, Seekout etc",
    otherTools: ""
  },
  {
    id: "16427701",
    firstName: "Claudia",
    lastName: "Sneddon Da Silva Raposo",
    jobTitle: "Global HRIS DIrector and HRD UK NAM",
    company: "Expleo Group",
    companySize: "10,001-20,000",
    industry: "Information Technology and Services",
    teamSize: "2001-5000",
    budgetAuthority: "Direct Approver",
    assessmentTool: "None",
    ats: "iCIMS",
    crm: "iCIMS LinkedIn",
    marketIntelligence: "Oracle",
    otherTools: ""
  },
  {
    id: "7258470500",
    firstName: "Mark",
    lastName: "Brooker",
    jobTitle: "TA Director",
    company: "BT Group",
    companySize: "50,001-100,000",
    industry: "Telecommunications",
    teamSize: "5001+",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "Sapia, SHL, Korn Ferry",
    ats: "Success Factors",
    crm: "N/A",
    marketIntelligence: "Horsefly",
    otherTools: "Topscore, Metaview, Real Links"
  },
  {
    id: "93380106578",
    firstName: "Peter",
    lastName: "Buchanan-Parker",
    jobTitle: "Executive Director, Talent Acquisition",
    company: "JPMorganChase",
    companySize: "100,000+",
    industry: "Financial Services",
    teamSize: "5001+",
    budgetAuthority: "Key Influencer",
    assessmentTool: "mixed - HireVire",
    ats: "Oracle Cloud",
    crm: "Oracle Cloud",
    marketIntelligence: "multiple",
    otherTools: ""
  },
  {
    id: "191181016455",
    firstName: "Nikhilesh",
    lastName: "Mathur",
    jobTitle: "nikhilesh.mathurlseg.com",
    company: "London Stock Exchange Group",
    companySize: "20,001-50,000",
    industry: "Financial Services",
    teamSize: "2001-5000",
    budgetAuthority: "Key Influencer",
    assessmentTool: "Codility, Cappfinity",
    ats: "Workday",
    crm: "Beamery",
    marketIntelligence: "LinkedIn Talent Insights",
    otherTools: ""
  },
  {
    id: "12731251",
    firstName: "James",
    lastName: "Boyle",
    jobTitle: "Director of Global Associate Recruiting",
    company: "Latham & Watkins",
    companySize: "5001-10,000",
    industry: "Law Practice",
    teamSize: "2001-5000",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "Cappfinity",
    ats: "iCIMS",
    crm: "iCIMS",
    marketIntelligence: "Pirical, Leopard, Firm Prospects",
    otherTools: ""
  },
  {
    id: "91862577670",
    firstName: "Lisa",
    lastName: "Brignall",
    jobTitle: "Head of TA, GB",
    company: "Coca-Cola Europacific partners",
    companySize: "20,001-50,000",
    industry: "Consumer Goods",
    teamSize: "1001-2000",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "Talogy",
    ats: "Successfactors",
    crm: "Eightfold",
    marketIntelligence: "Horsefly",
    otherTools: ""
  },
  {
    id: "9477501",
    firstName: "Edwin",
    lastName: "Pene",
    jobTitle: "Global Head of TA Operations",
    company: "Red Bull",
    companySize: "20,001-50,000",
    industry: "Food & Beverages",
    teamSize: "5001+",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "HireVue, Red Bull Wingfinder, PillarHR",
    ats: "SmartRecruiters",
    crm: "SmartRecruiters",
    marketIntelligence: "LinkedIn Talent Insights",
    otherTools: ""
  },
  {
    id: "8952301",
    firstName: "Chris",
    lastName: "Tennant",
    jobTitle: "VP Talent Acquisition",
    company: "Infor",
    companySize: "10,001-20,000",
    industry: "Computer Software",
    teamSize: "2001-5000",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "None",
    ats: "Pinpoint from June",
    crm: "Pinpoint from June",
    marketIntelligence: "None",
    otherTools: ""
  },
  {
    id: "8713772",
    firstName: "Alan",
    lastName: "MacKinnon",
    jobTitle: "Senior Director of TA (EMEA and APAC)",
    company: "Smith and Nephew plc",
    companySize: "10,001-20,000",
    industry: "Medical Devices",
    teamSize: "2001-5000",
    budgetAuthority: "Key Influencer",
    assessmentTool: "SHL",
    ats: "Workday",
    crm: "Workday CE",
    marketIntelligence: "Talent Neuron",
    otherTools: ""
  },
  {
    id: "192905181704",
    firstName: "Theresa",
    lastName: "O'Brien",
    jobTitle: "Global Head of Talent Acquisition",
    company: "CBRE",
    companySize: "100,000+",
    industry: "Facilities Services",
    teamSize: "5001+",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "SHL & Thomas international",
    ats: "Avature",
    crm: "Avature",
    marketIntelligence: "NA",
    otherTools: ""
  },
  {
    id: "8196151",
    firstName: "Michelle",
    lastName: "Monahan",
    jobTitle: "Head of Recruitment",
    company: "European Tyre Enterprise Limited",
    companySize: "5001-10,000",
    industry: "Automotive",
    teamSize: "1001-2000",
    budgetAuthority: "Key Influencer",
    assessmentTool: "we don't have one",
    ats: "TalentLink",
    crm: "we don't have one",
    marketIntelligence: "we don't have one",
    otherTools: ""
  },
  {
    id: "92953690026",
    firstName: "Oliver",
    lastName: "Browne",
    jobTitle: "Global Head of Talent Acquisition",
    company: "Lockton",
    companySize: "10,001-20,000",
    industry: "Insurance",
    teamSize: "2001-5000",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "SHL",
    ats: "People soft",
    crm: "None",
    marketIntelligence: "Building",
    otherTools: "LinkedIn, US Sourcing tools, Handshake etc"
  },
  {
    id: "4956154",
    firstName: "Jules",
    lastName: "Anderson",
    jobTitle: "Senior Director, Talent Acquisition and Global Mobility",
    company: "Gilead Science",
    companySize: "10,001-20,000",
    industry: "Biotechnology",
    teamSize: "2001-5000",
    budgetAuthority: "Direct Approver",
    assessmentTool: "None",
    ats: "Workday",
    crm: "Yello (terrible needs to be replaced, good for event management)",
    marketIntelligence: "Linked In recruiter",
    otherTools: ""
  },
  {
    id: "190937723960",
    firstName: "Natalie",
    lastName: "McGuinness",
    jobTitle: "Head of Talent Acquisition",
    company: "Busy Bees Nurseries",
    companySize: "10,001-20,000",
    industry: "Primary/Secondary Education",
    teamSize: "2001-5000",
    budgetAuthority: "Key Influencer",
    assessmentTool: "N/A",
    ats: "iCIMS",
    crm: "N/a",
    marketIntelligence: "N/a",
    otherTools: ""
  },
  {
    id: "5140258",
    firstName: "Sarah",
    lastName: "Cooper",
    jobTitle: "Group HR Technology, Insights and Recruitment Director",
    company: "Rentokil Initial",
    companySize: "50,001-100,000",
    industry: "Other",
    teamSize: "5001+",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "Vervoe",
    ats: "Workable, Workday and SmartRecruiters",
    crm: "Recruitment Smart",
    marketIntelligence: "Linkedin",
    otherTools: ""
  },
  {
    id: "91862579761",
    firstName: "Laura",
    lastName: "Callaghan",
    jobTitle: "Global Talent Acquisition Leader",
    company: "Western Union",
    companySize: "5001-10,000",
    industry: "Financial Services",
    teamSize: "1001-2000",
    budgetAuthority: "Key Influencer",
    assessmentTool: "Criteria",
    ats: "Workday",
    crm: "NA",
    marketIntelligence: "Talent insights",
    otherTools: "Paradox"
  },
  {
    id: "910801",
    firstName: "Caroline",
    lastName: "Loubert",
    jobTitle: "Global Head of TA",
    company: "Argus Media Ltd",
    companySize: "1001-2500",
    industry: "Information Services",
    teamSize: "251-500",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "Predictive Index",
    ats: "Teamtailor",
    crm: "Salesforce",
    marketIntelligence: "LinkedIn",
    otherTools: "HRIS - Workday"
  },
  {
    id: "9322701",
    firstName: "Tush",
    lastName: "Wijeratne",
    jobTitle: "Global Director of Talent Acquisition",
    company: "WPP",
    companySize: "100,000+",
    industry: "Marketing and Advertising",
    teamSize: "1001-2000",
    budgetAuthority: "Key Influencer",
    assessmentTool: "N/A",
    ats: "Greenhouse",
    crm: "Greenhouse",
    marketIntelligence: "Talent Neuron",
    otherTools: "LinkedIn and Hireze"
  },
  {
    id: "93174643474",
    firstName: "Salina",
    lastName: "Budaly",
    jobTitle: "Global TA Leader",
    company: "Balfour Beatty",
    companySize: "1001-2500",
    industry: "Construction",
    teamSize: "1001-2000",
    budgetAuthority: "Direct Approver",
    assessmentTool: "None",
    ats: "Talent Link",
    crm: "Beamary",
    marketIntelligence: "LinkedIn Insights",
    otherTools: ""
  },
  {
    id: "93137898669",
    firstName: "Jennifer",
    lastName: "Cunningham",
    jobTitle: "Vice president global recruiting",
    company: "Pearson",
    companySize: "10,001-20,000",
    industry: "Education Management",
    teamSize: "5001+",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "Gallup, Codility",
    ats: "Oracle",
    crm: "none",
    marketIntelligence: "Talent Insights and internal People analytics team",
    otherTools: "SnOW, CoPilot Studio, Fathem & Credly"
  },
  {
    id: "92353346050",
    firstName: "Debbie",
    lastName: "Robinson",
    jobTitle: "TA COE Strategy Lead",
    company: "PepsiCo",
    companySize: "100,000+",
    industry: "Food Production",
    teamSize: "5001+",
    budgetAuthority: "Key Influencer",
    assessmentTool: "Inhouse - PEPhire",
    ats: "iCIMS",
    crm: "iCIMS",
    marketIntelligence: "Draup, LinkedIn Talent Insights, Talent Neuron.",
    otherTools: "Pillar"
  },
  {
    id: "13454401",
    firstName: "Mark",
    lastName: "Coad",
    jobTitle: "Director, Talent Acquisition Transformation",
    company: "GSK",
    companySize: "50,001-100,000",
    industry: "Pharmaceuticals",
    teamSize: "5001+",
    budgetAuthority: "Direct Approver",
    assessmentTool: "SHL",
    ats: "Workday",
    crm: "Phenom",
    marketIntelligence: "LinkedIn",
    otherTools: ""
  },
  {
    id: "1076201",
    firstName: "Jon",
    lastName: "Warwick",
    jobTitle: "Group Director TA",
    company: "Sky",
    companySize: "20,001-50,000",
    industry: "Broadcast Media",
    teamSize: "2001-5000",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "Sova, SHL, Cappfinity, Codility",
    ats: "Workday",
    crm: "TUX",
    marketIntelligence: "Horesfly",
    otherTools: ""
  },
  {
    id: "452351",
    firstName: "Cath",
    lastName: "Possamai",
    jobTitle: "TA Director",
    company: "Amazon",
    companySize: "100,000+",
    industry: "Retail",
    teamSize: "5001+",
    budgetAuthority: "Final Budget Holder",
    assessmentTool: "All bespoke, in house",
    ats: "HIRE (bespoke, in house)",
    crm: "HIRE (bespoke, in house)",
    marketIntelligence: "In house",
    otherTools: ""
  }
];
