CREATE TABLE `intakeSubmissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sponsorId` int NOT NULL,
	`userId` int NOT NULL,
	`companyName` varchar(255) NOT NULL,
	`technologyType` varchar(255) NOT NULL,
	`companyLogoUrl` text,
	`companyBoilerplate` text NOT NULL,
	`keyChallenges` text NOT NULL,
	`targetOrgSize` varchar(255) NOT NULL,
	`firstName` varchar(255) NOT NULL,
	`lastName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`jobTitle` varchar(255) NOT NULL,
	`linkedinUrl` text NOT NULL,
	`secondRepName` varchar(255),
	`secondRepEmail` varchar(320),
	`secondRepJobTitle` varchar(255),
	`secondRepLinkedinUrl` text,
	`meetingPackage` enum('12','20') NOT NULL DEFAULT '12',
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `intakeSubmissions_id` PRIMARY KEY(`id`)
);
