export interface Attendee {
  id: string;
  firstName: string;
  lastName: string;
  jobTitle: string;
  company: string;
  companySize: string;
  industry: string;
  teamSize: string;
  budgetAuthority: string;
  assessmentTool: string;
  ats: string;
  crm: string;
  marketIntelligence: string;
  otherTools: string;
  // New fields from HubSpot CSV
  activeConfirmedProjects?: string;
  activeBudgetRange?: string;
  primaryMeetingObjective?: string;
  contractSignOff?: string;
  keySolutionAreasOfInterest?: string;
  currentPainPoints?: string;
  currentProjectStage?: string;
  regionalRemit?: string;
}

export const attendees: Attendee[] = [
  {
    "id": "4956154",
    "firstName": "Jules",
    "lastName": "Anderson",
    "jobTitle": "Senior Director, Talent Acquisition and Global Mobility",
    "company": "Gilead Science",
    "companySize": "10,001-20,000",
    "industry": "Biotechnology",
    "teamSize": "2001-5000",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "None",
    "ats": "Workday",
    "crm": "Yello (terrible needs to be replaced, good for event management)",
    "marketIntelligence": "Linked In recruiter",
    "otherTools": "",
    "activeConfirmedProjects": "New CRM and candidate experience tech system and AI enabled screening tool + new EVP",
    "activeBudgetRange": "> £1m",
    "primaryMeetingObjective": "AI enabled tech, candidate experience, recruiter efficiency, talen development and internal mobility.",
    "contractSignOff": "> £1m",
    "keySolutionAreasOfInterest": "As above - both but for the tech vendor support specifically mid 2026.",
    "currentPainPoints": "Candidate Screening, Internal Mobility, talent development within TA, collaboration and engagement, candidate experience, employer branding",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "Other"
  },
  {
    "id": "76678269091",
    "firstName": "Adam",
    "lastName": "Binks",
    "jobTitle": "Global Strategic Resourcing Lead",
    "company": "KPMG",
    "companySize": "100,000+",
    "industry": "Accounting",
    "teamSize": "5001+",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "Various across our network",
    "ats": "Various- We have over 40 ATSs in our network, main vendor is SAP SF",
    "crm": "Various across our network",
    "marketIntelligence": "Various across our network including Phenom and Eightfold",
    "otherTools": "",
    "activeConfirmedProjects": "TA Credential programme, EVP refresh, Hiring manager enablement, AI use cases for TA",
    "activeBudgetRange": "£50-100k",
    "primaryMeetingObjective": "Global capability of vendors, ability to deploy as stand alone product and integrate with local ATSs but also have ability to consolidate into large enterprise HCM tools",
    "contractSignOff": "£500K-£1m",
    "keySolutionAreasOfInterest": "As above",
    "currentPainPoints": "AI usage in TA across our member firm network, recruiter and hiring manager enablement, Recruiter training, EVP refresh.",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "Other"
  },
  {
    "id": "91889321035",
    "firstName": "Lucy",
    "lastName": "Bousfield",
    "jobTitle": "Global Head of talent Acquisition & Global Mobility",
    "company": "Aon",
    "companySize": "50,001-100,000",
    "industry": "Financial Services",
    "teamSize": "5001+",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "AAS",
    "ats": "ICIMS",
    "crm": "ICIMS",
    "marketIntelligence": "Gartner and Linkedin",
    "otherTools": "",
    "activeConfirmedProjects": "Assessment framework, Sourcing optimisation, Candidate experience",
    "activeBudgetRange": "£500k-£1m",
    "primaryMeetingObjective": "I want to connect to understand how others are navigating the everchanging talent landscape with AI solutions, digital transformation and optimisation of operating model.",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "Sourcing, employer brand, early careers, AI automation, talent intelligence",
    "currentPainPoints": "Driving assessment strategy and framework, sourcing optimisation, early careers strategy impacted by AI and transformation, Implementating talent marketplace and skills based strategy",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "Other"
  },
  {
    "id": "12731251",
    "firstName": "James",
    "lastName": "Boyle",
    "jobTitle": "Director of Global Associate Recruiting ",
    "company": "Latham & Watkins",
    "companySize": "5001-10,000",
    "industry": "Law Practice",
    "teamSize": "2001-5000",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "Cappfinity",
    "ats": "iCIMS",
    "crm": "iCIMS",
    "marketIntelligence": "Pirical, Leopard, Firm Prospects ",
    "otherTools": "",
    "activeConfirmedProjects": "ATS, Employer Branding, AI ",
    "activeBudgetRange": "£500k-£1m",
    "primaryMeetingObjective": "I am responsible for building a best in class recruiting function with global cohesion and technology/ AI enabled. I also would like to enhance our brand and meet with other global TA leaders on how they are thinking about the evolution of the function. ",
    "contractSignOff": "£500K-£1m",
    "keySolutionAreasOfInterest": "AI ",
    "currentPainPoints": "Assessment & Selection, AI add on to ATS, Employer branding/ activation specialists globally. ",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "Other"
  },
  {
    "id": "91862577670",
    "firstName": "Lisa",
    "lastName": "Brignal",
    "jobTitle": "Head of TA, GB",
    "company": "Coca-Cola Europacific partners",
    "companySize": "20,001-50,000",
    "industry": "Consumer Goods",
    "teamSize": "1001-2000",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "Talogy",
    "ats": "Successfactors",
    "crm": "Eightfold",
    "marketIntelligence": "Horsefly",
    "otherTools": "",
    "activeConfirmedProjects": "Technology and process optimisation; employer branding and skills based hiring (capabilities and embedding)",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "I want to learn more about tech out there that can support overall goals to optimise processes; particularly interested in programmatic, AI developments for sourcing; employer branding and data sources; id  like to share and understand key trends in the market and take the opportunity to learn across and build networks. ",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "Programmatic and AI enabled tech.",
    "currentPainPoints": "Evolving the TA function to be more proactive and strategic, Humanising AI in processes; inclusive hiring. Evolving capabilities of teams. ",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "UK"
  },
  {
    "id": "7258470500",
    "firstName": "Mark",
    "lastName": "Brooker",
    "jobTitle": "TA Director",
    "company": "BT Group",
    "companySize": "50,001-100,000",
    "industry": "Telecommunications",
    "teamSize": "5001+",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "Sapia, SHL, Korn Ferry",
    "ats": "Success Factors",
    "crm": "N/A",
    "marketIntelligence": "Horsefly",
    "otherTools": "Topscore, Metaview, Real Links",
    "activeConfirmedProjects": "Sourcing automation\nNew ATS\nOrg restructuring \nSkills hiring",
    "activeBudgetRange": "£500k-£1m",
    "primaryMeetingObjective": "Fresh thinking and networking",
    "contractSignOff": "> £1m",
    "keySolutionAreasOfInterest": "Agentic AI\nSourcing automation",
    "currentPainPoints": "Reducing team budgets whilst not reducing quality; blending technology with human endeavour; skills based hiring",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "UK, APAC"
  },
  {
    "id": "92953690026",
    "firstName": "Oliver",
    "lastName": "Browne",
    "jobTitle": "Global Head of Talent Acquisition",
    "company": "Lockton",
    "companySize": "10,001-20,000",
    "industry": "Insurance",
    "teamSize": "2001-5000",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "SHL",
    "ats": "People soft",
    "crm": "None",
    "marketIntelligence": "Building",
    "otherTools": "LinkedIn, US Sourcing tools, Handshake etc",
    "activeConfirmedProjects": "Talent Marketing, Talent Intelligence and Global Technology implementation and change",
    "activeBudgetRange": "> £1m",
    "primaryMeetingObjective": "Networking with like minded people with global knowledge",
    "contractSignOff": "> £1m",
    "keySolutionAreasOfInterest": "Talent Intelligence",
    "currentPainPoints": "Tech Implementation and Global TA Transformation",
    "currentProjectStage": "Planning & Budgeting (3-6 Months)",
    "regionalRemit": "EMEA, LATAM, UK, North America, UK&I, APAC, MENA"
  },
  {
    "id": "93380106578",
    "firstName": "Peter",
    "lastName": "Buchanan-Parker",
    "jobTitle": "Executive Director, Talent Acquisition",
    "company": "JPMorganChase",
    "companySize": "100,000+",
    "industry": "Financial Services",
    "teamSize": "5001+",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "mixed - HireVire",
    "ats": "Oracle Cloud",
    "crm": "Oracle Cloud",
    "marketIntelligence": "multiple",
    "otherTools": "",
    "activeConfirmedProjects": "ATS\nAssessments\nCandidate Satisfaction",
    "activeBudgetRange": "> £1m",
    "primaryMeetingObjective": ".",
    "contractSignOff": "< £50k",
    "keySolutionAreasOfInterest": "above",
    "currentPainPoints": "",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA,LATAM,North America,APAC,MENA"
  },
  {
    "id": "93174643474",
    "firstName": "Salina",
    "lastName": "Budaly",
    "jobTitle": "Global TA Leader ",
    "company": "Balfour Beatty",
    "companySize": "1001-2500",
    "industry": "Construction",
    "teamSize": "1001-2000",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "None ",
    "ats": "Talent Link",
    "crm": "Beamary ",
    "marketIntelligence": "LinkedIn Insights ",
    "otherTools": "",
    "activeConfirmedProjects": "AI, ATS EVP ",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "I would like to explore vendors to support a TA transformation ",
    "contractSignOff": "£500K-£1m",
    "keySolutionAreasOfInterest": "Talent Insight, EVP",
    "currentPainPoints": "Cost per application volume applications quality candidates",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "UK&I"
  },
  {
    "id": "150796696175",
    "firstName": "Jennifer",
    "lastName": "Candee",
    "jobTitle": "Global VP TA",
    "company": "Prior IMI, Cargill, Mondelez",
    "companySize": "10,001-20,000",
    "industry": "Mechanical or Industrial Engineering",
    "teamSize": "2001-5000",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "TBC ",
    "ats": "TBC ",
    "crm": "TBC ",
    "marketIntelligence": "TBC ",
    "otherTools": "",
    "activeConfirmedProjects": "TBC. In between roles ",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "Interviewing now for global vp ta roles both consultancy and perm. Look to multinational ai solutions integrate well into global enterprise ats ",
    "contractSignOff": "£50-100k",
    "keySolutionAreasOfInterest": "TBC ",
    "currentPainPoints": "TBC based on new contract or perm role ",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "Other"
  },
  {
    "id": "13454401",
    "firstName": "Mark",
    "lastName": "Coad",
    "jobTitle": "Director, Talent Acquisition Transformation ",
    "company": "GSK",
    "companySize": "50,001-100,000",
    "industry": "Pharmaceuticals",
    "teamSize": "5001+",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "SHL",
    "ats": "Workday",
    "crm": "Phenom",
    "marketIntelligence": "LinkedIn",
    "otherTools": "",
    "activeConfirmedProjects": "CRM launch, Agentic AI, offshoring",
    "activeBudgetRange": "> £1m",
    "primaryMeetingObjective": "Sharing and learning from peers on their journey.",
    "contractSignOff": "> £1m",
    "keySolutionAreasOfInterest": "Translation services, RPO, AI",
    "currentPainPoints": "Delivering financial savings via simplification, AI embedment and offshoring is challenging whilst delivering consistent service experience.  ",
    "currentProjectStage": "Planning & Budgeting (3-6 Months)",
    "regionalRemit": "Other"
  },
  {
    "id": "194295425320",
    "firstName": "robyn",
    "lastName": "collins",
    "jobTitle": "VP TA",
    "company": "M42",
    "companySize": "20,001-50,000",
    "industry": "Hospital & Health Care",
    "teamSize": "2001-5000",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "Building a global bank of assessments by function and level",
    "ats": "iCIMS and Success Factors",
    "crm": "iCIMS Jibe",
    "marketIntelligence": "NIL",
    "otherTools": "",
    "activeConfirmedProjects": "Review of iCIMS with a view to replace, deploy Findem for sourcing tech.",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "To meet liked minded global TA to network and learn, solve real tangible issues.",
    "contractSignOff": "> £1m",
    "keySolutionAreasOfInterest": "I am currently focused on building stronger recruiter and manager capability (building a \"licence to hire\" series) while redesigning the recruitment process namely for volume hiring, moving away from CV driven, application heavy processes using SJT and conversational AI and automated interview scheduling to replace resume applications with faster, more human decision making. ",
    "currentPainPoints": "Talent Acquisition operates at significant scale across trad healthcare, technology, and science/research, creating a set of interconnected challenges. Hiring demand is high, urgent, and specialised, while traditional recruitment models remain too resume driven, reactive, and process heavy to keep pace. Manager capability in hiring is inconsistent, leading to variable assessment quality, cost driven, and poor decision making.\nCandidate experience is fragmented due to legacy application flows and manual touchpoints.\nFinally, data and technology are under utilised, limiting visibility on impactful data making it harder to shift from transactional recruitment to a scalable, intelligence led talent engine.",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "EMEA,UK,LATAM,North America,UK&I,APAC,MENA"
  },
  {
    "id": "5140258",
    "firstName": "Sarah",
    "lastName": "Cooper",
    "jobTitle": "Group HR Technology, Insights and Recruitment Director",
    "company": "Rentokil Initial",
    "companySize": "50,001-100,000",
    "industry": "Other",
    "teamSize": "5001+",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "Vervoe",
    "ats": "Workable, Workday and SmartRecruiters",
    "crm": "Recruitment Smart",
    "marketIntelligence": "Linkedin",
    "otherTools": "",
    "activeConfirmedProjects": "ATS\nSkills Assessment\nCareersite enhancement",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "To see how I can pilot and scale across a challenging devolved tech stack. To either enhance Workday or to use an alternative ATS with solid global language offerings",
    "contractSignOff": "£500K-£1m",
    "keySolutionAreasOfInterest": "ATS\nSkills Assessment\nCareersite enhancement",
    "currentPainPoints": "ATS",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "EMEA, UK, LATAM, North America, UK&I, APAC, MENA"
  },
  {
    "id": "93137898669",
    "firstName": "Jennifer",
    "lastName": "Cunningham",
    "jobTitle": "Vice president global recruiting",
    "company": "Pearson",
    "companySize": "10,001-20,000",
    "industry": "Education Management",
    "teamSize": "5001+",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "Gallup, Codility",
    "ats": "Oracle",
    "crm": "none",
    "marketIntelligence": "Talent Insights and internal People analytics team",
    "otherTools": "SnOW, CoPilot Studio, Fathem & Credly",
    "activeConfirmedProjects": "Background Vendor Selection. Assessment Selection, Automation",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "understanding solutions and best practice on the challenges outlined above",
    "contractSignOff": "> £1m",
    "keySolutionAreasOfInterest": "Weeding out and assessing for fakes in SW engineering specifically",
    "currentPainPoints": "Rise of AI generated applications and Fake profiles driving TTH up while increasing recruiter frustrations. Supply and demand of Technology candidates and the need to be more creative on approach. Diversification of Geo's creating extra complexities on administration resource. Ai and automation as a User case. Need for validated and robust Assessment and selection  tools",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA, LATAM, North America, UK&I, APAC, MENA"
  },
  {
    "id": "17812226737",
    "firstName": "Rikki",
    "lastName": "Fullerton",
    "jobTitle": "Talent Acquisition Director",
    "company": "Serco",
    "companySize": "50,001-100,000",
    "industry": "Other",
    "teamSize": "5001+",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "AON",
    "ats": "Success Factors",
    "crm": "Phenom ",
    "marketIntelligence": "Talent Hub (SAP)",
    "otherTools": "",
    "activeConfirmedProjects": "Assessment, vetting & on-boarding ",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "I would like to get a better understanding of the latest capabilities (inc AI) of technology in the assessment, vetting & on-boarding space and the value they would bring to our organisation. ",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "Assessment, vetting, on-boarding",
    "currentPainPoints": "We are currently reviewing how assessments can improve quality of hire and therefore reduce attrition, which is a strategic focus for Serco. I am also keen to look at technology in both vetting & on-boarding. We have a team of 40+ currently managing our vetting and on-boarding processes, and I am keen to introduce more advanced tech to improve efficiency and reduce processing time.",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "UK,Other"
  },
  {
    "id": "113145184682",
    "firstName": "Carly",
    "lastName": "George",
    "jobTitle": "Head of Talent Acquisition",
    "company": "AXA",
    "companySize": "100,000+",
    "industry": "Insurance",
    "teamSize": "1001-2000",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "Korn Ferry, Arctic Shores",
    "ats": "ICIMS",
    "crm": "ICIMS",
    "marketIntelligence": "n/a",
    "otherTools": "",
    "activeConfirmedProjects": "Automation, Sourcing Agent, Interview Scheduling, Talent Intelligence, ",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "Ultimately I'm looking for vendors who can bring insight , challenge and perspective, that can help to shape future capability, cut through complexity and demonstrate measurable impact, supporting new ways of working in an AI enabled world whilst striking the balance between innovation and governance",
    "contractSignOff": "> £1m",
    "keySolutionAreasOfInterest": "Areas of interest include talent intelligence, advanced sourcing agents, skills based assessment methodology, executive assessment methodology, interview scheduling and coordination technology, enhanced data and analytics capability, VMS technology and Total Workforce Solutions",
    "currentPainPoints": "Our TA function operates as an end to end enterprise model covering attraction, sourcing, assessment, selection and offer management across executive, specialist, volume, early careers and contingent recruitment. Having recently implemented a new ATS and CRM, with a new external careers site about to launch, we are now engaging the market to explore how our recruitment ecosystem can be optimised. ",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "UK,UK&I"
  },
  {
    "id": "200101377371",
    "firstName": "Jessica Shaunie",
    "lastName": "Green",
    "jobTitle": "Head of talent acquisition",
    "company": "Calor gas",
    "companySize": "5001-10,000",
    "industry": "Oil & Energy",
    "teamSize": "1001-2000",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "Korn ferry ",
    "ats": "Workday ",
    "crm": "Pageup ",
    "marketIntelligence": "N/a",
    "otherTools": "",
    "activeConfirmedProjects": "EVP, AI integration, process streamlining without compromising experience of the candidate, ",
    "activeBudgetRange": "> £1m",
    "primaryMeetingObjective": "Automisation and technology is a huge focus this year to incorporate. EVP too and our market brand, our CEO has put this into all leaders across the business KPI’s for this financial year ",
    "contractSignOff": "> £1m",
    "keySolutionAreasOfInterest": "ATS system, AI automisation, EVP, candidate experience",
    "currentPainPoints": "Brand awareness and marketing of our great culture. Technology to help the recruiters becoming business partners ",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "EMEA,UK,UK&I"
  },
  {
    "id": "174442448959",
    "firstName": "Joanna",
    "lastName": "Hackett",
    "jobTitle": "Group Talent Acquisition Excellence Lead",
    "company": "Howden",
    "companySize": "20,001-50,000",
    "industry": "Insurance",
    "teamSize": "5001+",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "Arctic shores ",
    "ats": "Workday ",
    "crm": "TBc",
    "marketIntelligence": "TBC",
    "otherTools": "",
    "activeConfirmedProjects": "MSP/SOW global; global workday and associates AI tech roll out; global onboarding optimisation;",
    "activeBudgetRange": "> £1m",
    "primaryMeetingObjective": "Reduced recruiter admin, better hiring manager and recruiter adoption, globally joined up systems  and data, global MSP to support with management of external workers, modular RPO to support with TA ecosystem optimisation, joined up global LMS",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "MSP/SOW vendor",
    "currentPainPoints": "Agency usage, need for global MSP/SOW vendor, AI and automation, system standardisation; need for global CRM",
    "currentProjectStage": "Planning & Budgeting (3-6 Months)",
    "regionalRemit": "EMEA,UK,LATAM,North America,UK&I,APAC,MENA,Other"
  },
  {
    "id": "116903349643",
    "firstName": "James",
    "lastName": "Harley",
    "jobTitle": "Global Head of Executive Hiring",
    "company": "Syngenta",
    "companySize": "50,001-100,000",
    "industry": "Chemicals",
    "teamSize": "2001-5000",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "Hogan ",
    "ats": "Smart Recruiters ",
    "crm": "Smart Recruiters ",
    "marketIntelligence": "In-house - TalentNeuron, Seekout etc",
    "otherTools": "",
    "activeConfirmedProjects": "CRM for Exec level population, maturing the exec hiring function (following its creation in late 2024), developing sourcing capability globally",
    "activeBudgetRange": "> £1m",
    "primaryMeetingObjective": "I've had limited interaction with those that are leading Executive Hiring or have implemented a solution in this space since i took on this new role with Syngenta",
    "contractSignOff": "£50-100k",
    "keySolutionAreasOfInterest": "CRM, Market Intel & Insight",
    "currentPainPoints": "Building a scalable Executive Hiring Function within in global business with consider needs in all regions.  We are aiming to balance building as a CoE but also impowering the regions to step up and hire at the senior end of our busines",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "Other"
  },
  {
    "id": "110260566550",
    "firstName": "Sonal",
    "lastName": "Jain",
    "jobTitle": "Global Head TA CoE",
    "company": "Nissan Motor Corporation",
    "companySize": "100,000+",
    "industry": "Automotive",
    "teamSize": "5001+",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "None",
    "ats": "Workday",
    "crm": "Workday",
    "marketIntelligence": "Linkedin",
    "otherTools": "",
    "activeConfirmedProjects": "Interview scheduling, WD integration, Screening tools",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "Interaction with other RL leaders",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "Future of recruitment",
    "currentPainPoints": "",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "Other"
  },
  {
    "id": "111228357473",
    "firstName": "Hollie",
    "lastName": "Jordan",
    "jobTitle": "Head of Global Talent Acquisition",
    "company": "Ramboll",
    "companySize": "10,001-20,000",
    "industry": "Other",
    "teamSize": "2001-5000",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "SHL",
    "ats": "SmartRecruiters",
    "crm": "SmartRecruiters",
    "marketIntelligence": "LinkedIn Talent Insights previously, nothing today",
    "otherTools": "Datapeople",
    "activeConfirmedProjects": "Global Talent Acquisition Procedure & Governance, Pay Transparency Implementation, Hiring Manager Enablement, Global Leadership & Executive Hiring Transformation, Strategic Workforce Planning Integration, Nearshoring Centre Development (Europe), Early Careers Global Transformation, Employer Brand Activation.",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "Our HRIS is Workday, we previously had the Recruiting Module and then moved to SmartRecruiters. We're not sure if SR is a long term solution for us. We're open to moving from SHL in the next 12 months also.",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "Assessments",
    "currentPainPoints": "Moving the business from “doing hiring” to trusting TA as the front door, consistency at global scale without losing local credibility, Hiring manager capability and accountability, leadership and executive hiring in a lean, risk-averse market, employer brand activation vs reality, strategic workforce planning that actually influences decisions and capacity vs ambition.",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA, North America, UK&I, APAC"
  },
  {
    "id": "195183358360",
    "firstName": "Anna",
    "lastName": "Katyal",
    "jobTitle": "Head of Talent Acquisition",
    "company": "BMS Group",
    "companySize": "1001-2500",
    "industry": "Insurance",
    "teamSize": "251-500",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "N/A",
    "ats": "N/A",
    "crm": "N/A",
    "marketIntelligence": "N/A",
    "otherTools": "",
    "activeConfirmedProjects": "Applicant Tracking System selection, Strategic hiring projects for growth",
    "activeBudgetRange": "£50-100k",
    "primaryMeetingObjective": "I want to understand how to become more efficient with the TA team, to increase quality of data in reporting and systems use, how to provide a consistent recruitment process globally no matter the location, how to increase ROI, dashboard value and reduce recruiter admin",
    "contractSignOff": "< £50k",
    "keySolutionAreasOfInterest": "Recruitment system and database, process for maximum efficiency",
    "currentPainPoints": "Talent Acquisition in BMS Group is still quite new, and our processes are manual without an ATS. Reporting is difficult, reliance on agencies is still there, and a lack of understanding of broader Talent Acquisition strategies and solutions in insurance and other industries proves to be difficult to inspire solutions for our own team. Quality of candidates in certain areas is decreasing, yet applications are on the rise which proves to be a distraction from hiring the top talent and key strategies of doing this, keeping key talent warm for when it may be the right time and what systems TA have in place to maximise efficiency. Investors are requesting better data, improved reporting, a shorter time to hire to remain competitive.",
    "currentProjectStage": "Planning & Budgeting (3-6 Months)",
    "regionalRemit": "UK,North America,APAC"
  },
  {
    "id": "190898269597",
    "firstName": "Jonathan",
    "lastName": "Kitterhing best",
    "jobTitle": "Global head of Talent Acquisition",
    "company": "Swiss Re Management Ltd",
    "companySize": "10,001-20,000",
    "industry": "Insurance",
    "teamSize": "2001-5000",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "RR bespoke, Hogan, SHL",
    "ats": "SAP SSF",
    "crm": "Phenom",
    "marketIntelligence": "SSF module",
    "otherTools": "IN house built Textio type tool, Talent Neuron, LI Insights, Social Talent",
    "activeConfirmedProjects": "TBC",
    "activeBudgetRange": "< £50k",
    "primaryMeetingObjective": "Undertsand others approach to TA Skill based hiring, EU Pay Directive and AI in TA",
    "contractSignOff": "£50-100k",
    "keySolutionAreasOfInterest": "Ai, Automation, org redesign to reduce HC",
    "currentPainPoints": "Ai, Simplification of tech stack to reduce HC. implementing Phenom with SAP SSF in place",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "EMEA, LATAM, North America, UK&I, APAC, MENA, Other"
  },
  {
    "id": "910801",
    "firstName": "Caroline",
    "lastName": "Loubert",
    "jobTitle": "Global Head of TA",
    "company": "Argus Media Ltd",
    "companySize": "1001-2500",
    "industry": "Information Services",
    "teamSize": "251-500",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "Predictive Index",
    "ats": "Teamtailor",
    "crm": "Salesforce",
    "marketIntelligence": "LinkedIn",
    "otherTools": "HRIS - Workday",
    "activeConfirmedProjects": "Integrate ATS with HRIS, Introduce a new scheduling tool, globalise recruitment process, automate processes and bring in AI, automate reporting.",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "I have 20 years plus recruitment experience and I have been with Argus for 8 years in that time we have grown from 800 employees to 1600 employees, I have implemented a new ATS and grown the TA function from 1 to 8 in this time, however I really would like the toolkit now to navigate the next stages of my career with more C level reporting and bringing new ideas to the function",
    "contractSignOff": "< £50k",
    "keySolutionAreasOfInterest": "Talent Sourcing, Employee Branding and Automated testing tools.",
    "currentPainPoints": "I have 20 years plus recruitment experience and I have been with Argus for 8 years in that time we have grown from 800 employees to 1600 employees, I have implemented a new ATS and grown the TA function from 1 to 8 in this time, however I really would like the toolkit now to navigate the next stages of my career with more C level reporting and bringing new ideas to the function",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA, UK, LATAM, North America, APAC, MENA"
  },
  {
    "id": "122796319563",
    "firstName": "Julie",
    "lastName": "Lowe",
    "jobTitle": "Head of Talent Acquisition",
    "company": "easyJet",
    "companySize": "20,001-50,000",
    "industry": "Airlines/Aviation",
    "teamSize": "2001-5000",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "AON",
    "ats": "Taleo",
    "crm": "None",
    "marketIntelligence": "LinkedIn Talent Insights",
    "otherTools": "",
    "activeConfirmedProjects": "ATS replacement\nAssessments upgrade\nEngagement tool\nCRM",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "How do demonstrate ROI, What solutions are available, how to move from behind the curve to ahead. How to get AI into our process.",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "As above",
    "currentPainPoints": "ATS not fit for purpose, no automated for screening high volumes of applicants (100k plus per year), out of date assessments, no CRM, unable to keep candidates engaged in hold pools.",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "EMEA"
  },
  {
    "id": "8713772",
    "firstName": "Alan",
    "lastName": "MacKinnon",
    "jobTitle": "Senior Director of TA (EMEA and APAC)",
    "company": "Smith and Nephew plc",
    "companySize": "10,001-20,000",
    "industry": "Medical Devices",
    "teamSize": "2001-5000",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "SHL",
    "ats": "Workday",
    "crm": "Workday CE",
    "marketIntelligence": "Talent Neuron",
    "otherTools": "",
    "activeConfirmedProjects": "Background Checks\nContingent worker RPO and MSP\nSelection and assessment technology\nHiring Manager and end users education & support",
    "activeBudgetRange": "£500k-£1m",
    "primaryMeetingObjective": "Better understanding of how the solutions 'are better' than existing partnerships/solutions ; Approaches to implementation, adoption and realization of benefits",
    "contractSignOff": "< £50k",
    "keySolutionAreasOfInterest": "Contingent worker RPO",
    "currentPainPoints": "Balancing global consistency with regional relevance (legal, cultural, language etc) ; driving positive process and tech adoption across users and stakeholders ; Fully capitalizing on the benefits of Tech, AI & Automation while protecting the human experience of recruitment",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA,APAC"
  },
  {
    "id": "191181016455",
    "firstName": "Nikhilesh",
    "lastName": "Mathur",
    "jobTitle": "nikhilesh.mathurlseg.com",
    "company": "London Stock Exchange Group",
    "companySize": "20,001-50,000",
    "industry": "Financial Services",
    "teamSize": "2001-5000",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "Codility, Cappfinity",
    "ats": "Workday",
    "crm": "Beamery",
    "marketIntelligence": "LinkedIn Talent Insights",
    "otherTools": "",
    "activeConfirmedProjects": "Review Assessment Tools, Workday Adaptive, Hiredscore",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "Understand capability and cost of potential tools",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "Review Assessment Tools, Workday Adaptive, Hiredscore",
    "currentPainPoints": "Reviewing assessment tools to funnel good quality candidates through the application process. Also reviewing tools to engage with passive candidates and bring them to the table for opportunistic discussions.",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA,UK,LATAM,North America,UK&I,APAC,MENA,Other"
  },
  {
    "id": "11132851",
    "firstName": "Martin",
    "lastName": "McDermott",
    "jobTitle": "Global Director of Talent Acquisition ",
    "company": "IQ-EQ",
    "companySize": "5001-10,000",
    "industry": "Financial Services",
    "teamSize": "2001-5000",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "Hogan at leadership, Aon ",
    "ats": "Smart Recruiters",
    "crm": "HireEZ",
    "marketIntelligence": "None",
    "otherTools": "",
    "activeConfirmedProjects": "Adoption of Winston AI from Smart Recruiters in our tech stack, Onboarding portal solutions to go from hiring decision to candidate acceptance quickly ",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "We need to focus on technology that directly addresses our current challenges and can automate key stages of the end to end recruitment journey. Over the next two years we expect to explore the adoption of a global ERP, so our approach must balance both short term needs and longer term direction. In the short term, we require a solution that simplifies the hiring process and enhances the experience for candidates and hiring managers. Longer term, we will need a stronger user experience layer to complement the core ERP, recognising that major ERP vendors have not yet fully addressed the experience gaps that exist across the recruitment journey.",
    "contractSignOff": "£500K-£1m",
    "keySolutionAreasOfInterest": "CRM and Onboarding Solution tech to support top of the funnell",
    "currentPainPoints": "As we shift from a reactive Talent Acquisition model to an always on hiring approach, several challenges are limiting our ability to move quickly from hiring demand to shortlist to start date.\nHiring demand often reaches TA too late.\nThe business frequently signals resource needs only at the point of urgency. This compresses timelines, restricts our ability to pipeline, and forces reactive sourcing that slows down delivery.\nWe lack consistent, structured talent pipelines.\nSustained talent pools for repeatable and high volume roles are not yet embedded across our global function. Without active pipelines, creating a high quality shortlist takes significantly longer.\nProcesses and tools are creating friction instead of reducing it.\nOur workflows still include multiple handoffs, manual steps, and inconsistent adoption of platforms. These bottlenecks slow feedback, extend decision making, and create unnecessary delays throughout the hiring process.\nHiring manager readiness and expectations vary.\nDifferences in role scoping, interview capability, and feedback turnaround lead to avoidable delays. Where managers lack clarity or support, the hiring journey becomes slower and more complex.\nThe candidate experience is not designed for pace.\nSlow communication, long interview cycles, and inconsistent touchpoints negatively impact engagement. In competitive markets, this leads to candidate withdrawals and missed hiring opportunities.\nData is not yet predictive or operational.\nWhile we collect activity data, we do not have real time insights that forecast demand, highlight bottlenecks, or assess pipeline health. This keeps TA in a reactive posture rather than enabling proactive intervention.",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA,North America,APAC"
  },
  {
    "id": "190937723960",
    "firstName": "Natalie",
    "lastName": "McGuinness",
    "jobTitle": "Head of Talent Acquisition ",
    "company": "Busy Bees Nurseries",
    "companySize": "10,001-20,000",
    "industry": "Primary/Secondary Education",
    "teamSize": "2001-5000",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "N/A",
    "ats": "iCIMS",
    "crm": "N/a",
    "marketIntelligence": "N/a",
    "otherTools": "",
    "activeConfirmedProjects": "AI selection tools, MSP platform, Candidate experience, Talent pipe lining",
    "activeBudgetRange": "< £50k",
    "primaryMeetingObjective": "I want to be really clear on where AI adds value to a TA related activity and how to risk assess before creating a business case ",
    "contractSignOff": "< £50k",
    "keySolutionAreasOfInterest": "AI solutions ",
    "currentPainPoints": "Volume/quality ",
    "currentProjectStage": "Planning & Budgeting (3-6 Months)",
    "regionalRemit": "UK&I"
  },
  {
    "id": "8196151",
    "firstName": "Michelle",
    "lastName": "Monahan",
    "jobTitle": "Head of Recruitment",
    "company": "European Tyre Enterprise Limited",
    "companySize": "5001-10,000",
    "industry": "Automotive",
    "teamSize": "1001-2000",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "we don't have one",
    "ats": "TalentLink",
    "crm": "we don't have one",
    "marketIntelligence": "we don't have one",
    "otherTools": "",
    "activeConfirmedProjects": "1. Automation\n2.Have a 100 MOT roles coming down the line (additional headcount, there is a massive skills shortage in the Automotive Industry and MOT tester are like unicorns, our pay is average and the market highly competitive\n3.  From approx June I will get the go ahead to start advertising and will need to recruit 300 Apprentices 16-18 year olds to start between Sept and Nov.  Conscious will miss the school leavers who start looking from April onwards.  This a mammoth task, we normally recruit 300 apprentices across the year with a team of 2 recruiters and receive approx 18,000 applications, so conscious this is going to be condensed in to a small time frame.  How do manage that volume, deliver the result whilst ensuring candidate experience isn't impacted.\n4. Upskilling/team development.  Scared of technology, how I help, support and train.\n5.  Background checks for keys roles for Finance etc.",
    "activeBudgetRange": "< £50k",
    "primaryMeetingObjective": "What systems/software that are compatible and cost effective that can help me support with current projects and deliver what I need to the business that helps and supports the team to make us more efficient",
    "contractSignOff": "< £50k",
    "keySolutionAreasOfInterest": "Anything that can help me with the above",
    "currentPainPoints": "1. What I can automate in candidate process, without losing the human touch and missing out on talent, to ensure team is most productive and do what they do best.  This is more so for unskilled roles where attitude prevails over experience and where our highest volume of recruitment comes from.  Doing more with less headcount.",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "UK&I"
  },
  {
    "id": "200923910443",
    "firstName": "Nuria",
    "lastName": "Munoz",
    "jobTitle": "Head of Talent Acquisition Europe and Latin America",
    "company": "Munich Re",
    "companySize": "50,001-100,000",
    "industry": "Insurance",
    "teamSize": "2001-5000",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "Various vendors across the world, non consistent ",
    "ats": "Success Factors ",
    "crm": "None",
    "marketIntelligence": "Cobrainer",
    "otherTools": "",
    "activeConfirmedProjects": "SF migration to Smart Recruiters , Referral Platforms, GenAI for Recruitment , TA TOM, Early Careers , candidate assessment tools ",
    "activeBudgetRange": "£500k-£1m",
    "primaryMeetingObjective": "to secure a clear understanding of technology changes, success business cases and processes across the function ",
    "contractSignOff": "£500K-£1m",
    "keySolutionAreasOfInterest": "AI, Early Careers , Data Analytics for TA",
    "currentPainPoints": "The entire organisation is going under HR Transformation, there are multiple needs , from systems that do not speak to each other, to lack of data and processes in place. From a TA perspective Early Careers is an area of investment and potential AI near future to support recruitment ",
    "currentProjectStage": "Planning & Budgeting (3-6 Months)",
    "regionalRemit": "EMEA,UK,LATAM,UK&I"
  },
  {
    "id": "185464523694",
    "firstName": "David",
    "lastName": "Nottage",
    "jobTitle": "Head of TA",
    "company": "Screwfix",
    "companySize": "10,001-20,000",
    "industry": "Retail",
    "teamSize": "2001-5000",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "Multiple",
    "ats": "iCIMS",
    "crm": "SAP",
    "marketIntelligence": "N/A",
    "otherTools": "Various, but nothing outstanding",
    "activeConfirmedProjects": "Automation\nATS config and optimisation\nEmployer branding strategy\nTalent mapping and workforce planning \nSkills gap analysis and assessments",
    "activeBudgetRange": "> £1m",
    "primaryMeetingObjective": "I would like to have some conversations about not only solutions to issues we have now, but where are we going and how do I future proof the TA function for not only Screwfix, but also the wider Kingfisher Group including B&Q, Screwfix, Brico and more.",
    "contractSignOff": "£500K-£1m",
    "keySolutionAreasOfInterest": "all of the obove",
    "currentPainPoints": "I currently have a group wide ATS system, that si clunky so am working with them to maximise the potential of the system. In terms of the team,  they are very immature in terms of TA and have been doing a lot of manual processes. I am really interested in AI, releasing the teams to do more work that matters and thinking about the role we have to play both in talent acquisition and talent rejection.",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA"
  },
  {
    "id": "192905181704",
    "firstName": "Theresa",
    "lastName": "O’Brien",
    "jobTitle": "Global Head of TA",
    "company": "CBRE",
    "companySize": "100,000+",
    "industry": "Facilities Services",
    "teamSize": "5001+",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "SHL & Thomas international",
    "ats": "Avature",
    "crm": "Avature",
    "marketIntelligence": "NA",
    "otherTools": "",
    "activeConfirmedProjects": "Assessment & Selection refresh\nHiring manager recruitment & selection training \n5 year workforce plan",
    "activeBudgetRange": "£50-100k",
    "primaryMeetingObjective": "I want to identify best assessment & selection solutions for hiring for future needs",
    "contractSignOff": "> £1m",
    "keySolutionAreasOfInterest": "Assessment & selection",
    "currentPainPoints": "Scaling volume hiring at pace in countries without dedicated TA support\nEnsuring quality leadership hiring in fast paced candidate short markets\nRefreshing selection & psychometrics tools to meet future hiring needs",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "Other"
  },
  {
    "id": "201697440144",
    "firstName": "Ciaran",
    "lastName": "O'Regan",
    "jobTitle": "Director, Talent Acquisition",
    "company": "the LEGO Group",
    "companySize": "20,001-50,000",
    "industry": "Retail",
    "teamSize": "2001-5000",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "HireVue, Internal Interview Toolkit",
    "ats": "Workday",
    "crm": "N/A",
    "marketIntelligence": "LinkedIn Talent Insights, internal analytics and insights team using PowerBI",
    "otherTools": "",
    "activeConfirmedProjects": "Assessments, Structured Interviews, Candidate Experience Tools",
    "activeBudgetRange": "£50-100k",
    "primaryMeetingObjective": "Understand new tech and how these can solve future problems given advances in AI",
    "contractSignOff": "< £50k",
    "keySolutionAreasOfInterest": "Assessments",
    "currentPainPoints": "Detecting signal from high volume of applicants.  Looking at assessment technology that enables us to select the right candidates without effecting candidates experience negatively. \n\nTools to help with scaling structured interviews. ",
    "currentProjectStage": "Planning & Budgeting (3-6 Months)",
    "regionalRemit": "EMEA,UK,LATAM,North America,UK&I,APAC,MENA"
  },
  {
    "id": "194698768792",
    "firstName": "Nainik",
    "lastName": "Patel",
    "jobTitle": "Delivery Lead, Head of Global Talent Acquisition ",
    "company": "Hitachi",
    "companySize": "100,000+",
    "industry": "Information Technology and Services",
    "teamSize": "2001-5000",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "…",
    "ats": "Workday ",
    "crm": "…",
    "marketIntelligence": "…",
    "otherTools": "",
    "activeConfirmedProjects": "…",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "Building value case to introduce Ai/Technology to attract and retain talent  ",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "…",
    "currentPainPoints": "Candidate/new joiner and hiring manager experience ",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA,UK,North America,UK&I,APAC,MENA"
  },
  {
    "id": "9477501",
    "firstName": "Edwin",
    "lastName": "Pene",
    "jobTitle": "Global Head of TA Operations",
    "company": "Red Bull",
    "companySize": "20,001-50,000",
    "industry": "Food & Beverages",
    "teamSize": "5001+",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "HireVue, Red Bull Wingfinder, PillarHR",
    "ats": "SmartRecruiters",
    "crm": "SmartRecruiters",
    "marketIntelligence": "LinkedIn Talent Insights",
    "otherTools": "",
    "activeConfirmedProjects": "Early Careers process review, Hiring for Growth, Elevating Selection",
    "activeBudgetRange": "£500k-£1m",
    "primaryMeetingObjective": "Within our ecosystem, SmartRecruiters, what are some of the technologies that could help us with the volume of applications, so recruiters concentrate on the few good candidates, which ultimately should help in hiring faster without compromising the quality. They would need to fully integrate with SmartRecruiters, as we believe in a single source of truth and consolidated data reporting. ",
    "contractSignOff": "£50-100k",
    "keySolutionAreasOfInterest": "AI Screening (Top funnel), On-demand interview (High Volume Assessment), Ai Noteraker",
    "currentPainPoints": "Reduce time-to-hire without compromising quality of hire.  Hiring volume is one of the challenges; we have a high number of applicants (1000+), so how do we get to the few good profiles at the top of the funnel, while ensuring a positive candidate experience. \n\nOn a similar line, high-volume assessments for Early Careers and Sales roles.\n\nGet Hiring Managers to focus on interviewing with our framework and methods, without worrying about taking notes during interviews, and upskill them through coaching. ",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA,LATAM,North America,APAC,MENA"
  },
  {
    "id": "452351",
    "firstName": "Cath",
    "lastName": "Possamai",
    "jobTitle": "TA Director",
    "company": "Amazon",
    "companySize": "100,000+",
    "industry": "Retail",
    "teamSize": "5001+",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "All bespoke, in house",
    "ats": "HIRE (bespoke, in house)",
    "crm": "HIRE (bespoke, in house)",
    "marketIntelligence": "In house",
    "otherTools": "",
    "activeConfirmedProjects": "see above",
    "activeBudgetRange": "> £1m",
    "primaryMeetingObjective": "Networking with peers - understand how they are approaching similar challenges. Insight into what tech vendors are offering to inform our own roadmap (you might not like to read this but at least I am honest!)",
    "contractSignOff": "> £1m",
    "keySolutionAreasOfInterest": "See above",
    "currentPainPoints": "Improve Quality of Hire; Precision at scale in selection and assessment; standardisation of process and roles across a huge global TA team; agile and data led capacity sharing; demand planning. BUT - we build ALL our tech in house so although I am interested in what is out there I am really unlikely to buy anything!",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA, MENA"
  },
  {
    "id": "92353346050",
    "firstName": "Debbie",
    "lastName": "Robinson",
    "jobTitle": "TA COE Strategy Lead",
    "company": "PepsiCo",
    "companySize": "100,000+",
    "industry": "Food Production",
    "teamSize": "5001+",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "Inhouse - PEPhire",
    "ats": "iCIMS",
    "crm": "iCIMS",
    "marketIntelligence": "Draup, LinkedIn Talent Insights, Talent Neuron.",
    "otherTools": "Pillar",
    "activeConfirmedProjects": "Front Line ATS solution but vendor is selected (Paradox)",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "Understanding",
    "contractSignOff": "£50-100k",
    "keySolutionAreasOfInterest": "Early Talent, Assessment",
    "currentPainPoints": "We're focused on optimizing current solutions.  We are working on Global Early Talent and I don't think iCIMS is the solution for this.  I would also question whether our assessment solutions are fit for purpose.  I can influence but I'm not a decision maker on the technologies we choose - these decision are made from New York.",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA, Other"
  },
  {
    "id": "203946652193",
    "firstName": "joanna",
    "lastName": "saunders-hare",
    "jobTitle": "Executive Director, Talent Acquisition",
    "company": "MUFG, Mitsubishi UFJ Financial Group.",
    "companySize": "1001-2500",
    "industry": "Financial Services",
    "teamSize": "1001-2000",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "Assess Candidates ",
    "ats": "Smart Recruiters",
    "crm": "Smart Recruiters",
    "marketIntelligence": "LinkedIn Insights ",
    "otherTools": "",
    "activeConfirmedProjects": "5",
    "activeBudgetRange": "> £1m",
    "primaryMeetingObjective": "Defining the next 3-5 transformation plan for Talent Management (Acquisition & Development) ",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "AI, skills gaps & new market insights, end2end Talent Management, ROI on hire ",
    "currentPainPoints": "Identifying creative scalable tech to make hiring decisions. Upskilling TA teams to be consultative, using predictive analytics to build hiring strategies,  Quantifying skills gaps in talent pools, and plugging skills gaps. Identifying  new markets for growth with robust data,",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "Other"
  },
  {
    "id": "16427701",
    "firstName": "Claudia",
    "lastName": "Sneddon Da Silva Raposo",
    "jobTitle": "Global HRIS DIrector and HRD UK NAM",
    "company": "Expleo Group",
    "companySize": "10,001-20,000",
    "industry": "Information Technology and Services",
    "teamSize": "2001-5000",
    "budgetAuthority": "Direct Approver",
    "assessmentTool": "None",
    "ats": "iCIMS",
    "crm": "iCIMS LinkedIn",
    "marketIntelligence": "Oracle",
    "otherTools": "",
    "activeConfirmedProjects": "Review global ATS",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "Connect with likeminded people ",
    "contractSignOff": "< £50k",
    "keySolutionAreasOfInterest": "Competing with market salaries and our revenue",
    "currentPainPoints": "",
    "currentProjectStage": "Actively Evaluating Vendors",
    "regionalRemit": "UK,North America"
  },
  {
    "id": "8952301",
    "firstName": "Chris",
    "lastName": "Tennant",
    "jobTitle": "VP Talent Acquisition",
    "company": "Infor",
    "companySize": "10,001-20,000",
    "industry": "Computer Software",
    "teamSize": "2001-5000",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "None",
    "ats": "Pinpoint from June",
    "crm": "Pinpoint from June",
    "marketIntelligence": "None",
    "otherTools": "",
    "activeConfirmedProjects": "Implementation of ATS, Onboarding. ",
    "activeBudgetRange": "< £50k",
    "primaryMeetingObjective": "Gain a deeper knowledge of what I would need coming up",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "Would be interested in background checking vendors",
    "currentPainPoints": "Metrics will be improving and so will my effeciencies with the new ATS. Challenege will be how to scale the team to be more consultative",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA,UK,LATAM,North America,UK&I,APAC,MENA"
  },
  {
    "id": "1076201",
    "firstName": "Jon",
    "lastName": "Warwick",
    "jobTitle": "Group Director TA",
    "company": "Sky",
    "companySize": "20,001-50,000",
    "industry": "Broadcast Media",
    "teamSize": "2001-5000",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "Sova, SHL, Cappfinity, Codility",
    "ats": "Workday",
    "crm": "TUX",
    "marketIntelligence": "Horesfly",
    "otherTools": "",
    "activeConfirmedProjects": "Assessment Tech, RPO renewal, AI",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "Networking with peers and sharing ideas on future focus.",
    "contractSignOff": "> £1m",
    "keySolutionAreasOfInterest": "AI, Assessment tech, Talent Marketplace, Skills",
    "currentPainPoints": "",
    "currentProjectStage": "Planning & Budgeting (3-6 Months)",
    "regionalRemit": "EMEA"
  },
  {
    "id": "9322701",
    "firstName": "Tush",
    "lastName": "Wijeratne",
    "jobTitle": "Global Director of Talent Acquisition",
    "company": "WPP",
    "companySize": "100,000+",
    "industry": "Marketing and Advertising",
    "teamSize": "1001-2000",
    "budgetAuthority": "Key Influencer",
    "assessmentTool": "N/A",
    "ats": "Greenhouse",
    "crm": "Greenhouse",
    "marketIntelligence": "Talent Neuron",
    "otherTools": "LinkedIn and Hireze",
    "activeConfirmedProjects": "Offshore souring hubs / tooling - India \nLinkedIn alternatives\nAI usage identification tools in tech tests and interviews",
    "activeBudgetRange": "< £50k",
    "primaryMeetingObjective": "Keen to understand the leading industry techniques and tools which should be recommended for the future of talent acquisition at WPP as we gorgeous a global transformation. I am awaiting the new CEO’s vision and this should then help with future TA transformation and relevant budgets.",
    "contractSignOff": "< £50k",
    "keySolutionAreasOfInterest": "AI usage identification",
    "currentPainPoints": "Offshoring and restructure of TA",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA, North America, UK&I, APAC, Other"
  },
  {
    "id": "128491656706",
    "firstName": "Yuliia",
    "lastName": "Zembal",
    "jobTitle": "Head of Talent Acquisition ",
    "company": "UKRSIBBANK BNP PARIBAS GROUP",
    "companySize": "100,000+",
    "industry": "Banking",
    "teamSize": "1001-2000",
    "budgetAuthority": "Final Budget Holder",
    "assessmentTool": "SHL",
    "ats": "Avature ",
    "crm": "SAP",
    "marketIntelligence": " -",
    "otherTools": "",
    "activeConfirmedProjects": "AI implementation, process automation, IT employer Brand development, onboarding automation. ",
    "activeBudgetRange": "£100-500k",
    "primaryMeetingObjective": "I want to understand how can I implement AI instruments into TA processes in order to reduce time to hire and to save FTE. ",
    "contractSignOff": "£100-500k",
    "keySolutionAreasOfInterest": "Onboarding automation, AI instruments in TA",
    "currentPainPoints": "We are actively exploring vendors to implement AI instruments into TA processes but we should be very careful with the cybersecurity limitations. Also we are in the active stage of processes automation and looking for the instruments to improve experience on pre-onboarding and onboarding stages. We are exploring opportunities to improve time-to-hire of our mass positions in branches. ",
    "currentProjectStage": "Benchmarking for Future Use (6-12 Months)",
    "regionalRemit": "EMEA"
  }
];
